import { randomUUID } from "node:crypto";
import { z } from "zod";
import { canonical } from "@/lib/canonical";
import { evidenceZip } from "@/lib/evidence-zip";
import { contentHash, verifyEvidence } from "@/lib/evidence-verification";
import { db, serialized } from "./db";
import { mac, secureEqual } from "./config";
import { verifySignature } from "./memory";
import { CapacityError, ConflictError } from "./gateway";
import { invocationProof } from "@/lib/evaluation-contract";
import type { Prisma } from "@/generated/prisma/client";

export const evidenceScopeSchema = z.object({ kind: z.enum(["run", "incident", "hunt", "sentinel"]), id: z.string().uuid() }).strict();
const safeText = (s: string) => s.slice(0, 500).replace(/Bearer\s+\S+|sk-[a-zA-Z0-9_-]{8,}|(?:api[_ -]?key|password|secret|credential)\s*[:=]\s*\S+/gi, "[REDACTED]");
const metadataKeys = new Set(["memoryId", "memoryVersionId", "originalMemoryId", "restoredFromId", "sourceId", "sourceTrust", "rule", "reason", "allowed", "identityVerified", "protected", "integrityVerified", "originalIntact", "actionId", "enforcementVerified", "handlerNeverExecuted", "verificationRequestId", "simulated", "requestId", "incidentId", "invocationId", "mode", "experimentId", "phase", "handlerExecuted", "provenance", "messageId", "rootRequestId", "referenceRequestId", "planId", "attemptedContentHash", "sourceDocumentId", "tool", "operation", "resource", "baselineId", "baselineVersion", "previousRequestId"]);
function metadata(input: unknown): Record<string, string | number | boolean | null> {
  if (!input || typeof input !== "object" || Array.isArray(input)) return {};
  return Object.fromEntries(Object.entries(input).filter(([k, v]) => metadataKeys.has(k) && (v === null || ["string", "number", "boolean"].includes(typeof v))).map(([k, v]) => [k, typeof v === "string" ? safeText(v) : v])) as Record<string, string | number | boolean | null>;
}
const html = (v: unknown) => String(v ?? "Not recorded").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const manifestMac = (unsigned: string) => mac(`ghostops-evidence:v1:${unsigned}`);
/** Only authoritative request/hash-linked scans and persisted retrieval metadata enter the existing archive. */
async function sponsorEvidence(requestIds:string[],sourceIds:string[]) {
  const scans=await db.codeScan.findMany({where:{requestId:{in:requestIds}},take:101});if(scans.length>100)throw new CapacityError("Scan evidence capacity exceeded");
  const contextIds=sourceIds.filter(s=>/^sponsor-context:[a-f0-9-]{36}$/.test(s)).map(s=>s.slice(16));
  const sources=await db.integrationRun.findMany({where:{id:{in:contextIds},action:"context",status:"succeeded"},take:101});if(sources.length>100)throw new CapacityError("Context evidence capacity exceeded");
  return {codeScans:scans.map(s=>({id:s.id,requestId:s.requestId,target:s.target,scannerVersion:s.scannerVersion,ruleHash:s.ruleHash,files:s.files,findings:s.findings,comparison:s.comparison,commit:s.commit,createdAt:s.createdAt,limitation:"Pattern finding, not proof of compromise"})),contextSources:sources.map(r=>({id:r.id,mode:r.mode,createdAt:r.createdAt,result:r.result}))};
}
export async function exportEvidence(kind: "run" | "incident" | "hunt" | "sentinel", id: string) {
  evidenceScopeSchema.parse({ kind, id });
  if(kind==="sentinel")return (await import("./sentinel-evidence")).exportSentinelEvidence(id);
  if (kind === "hunt") return exportHuntEvidence(id);
  const createdAt = new Date().toISOString();
  const data = await serialized(() => db.$transaction(async tx => {
    const run = kind === "run" ? await tx.experimentRun.findUnique({ where: { id }, include: { observations: { orderBy: { ordinal: "asc" } }, invocations: { orderBy: { startedAt: "asc" } } } }) : null;
    if (kind === "run" && (!run || ["queued", "running"].includes(run.status))) throw new ConflictError("Export requires an existing terminal experiment");
    const incident = kind === "incident" ? await tx.incident.findUnique({ where: { id } }) : null;
    if (kind === "incident" && !incident) throw new ConflictError("Investigation not found");
    const ids = run?.observations.flatMap(o => o.requestId ? [o.requestId] : []) ?? [];
    const events = await tx.securityEvent.findMany({ where: kind === "run" ? { OR: [{ runId: id }, { requestId: { in: ids } }] } : { incidentId: id }, orderBy: { ordinal: "asc" }, take: 4001, include: { findings: true } });
    if (events.length > 4000) throw new CapacityError("Evidence exceeds export event capacity; no truncated report generated");
    const requestIds = [...new Set([...ids, ...events.flatMap(e => e.requestId ? [e.requestId] : [])])];
    const requests = await tx.toolRequest.findMany({ where: { id: { in: requestIds } }, orderBy: { createdAt: "asc" }, include: { decision: true } });
    const incidentIds = kind === "incident" ? [id] : [...new Set(events.flatMap(e => e.incidentId ? [e.incidentId] : []))];
    const incidents = await tx.incident.findMany({ where: { id: { in: incidentIds } }, include: { actions: true, evidence: true } });
    const interactions = await tx.trapInteraction.findMany({ where: { requestId: { in: requestIds } }, include: { trap: true } });
    const memoryIds = [...events.map(e => e.details), ...(run?.observations.map(o => o.details) ?? [])].flatMap(value => Object.entries(metadata(value)).filter(([k, v]) => /memoryId|memoryVersionId|originalMemoryId|restoredFromId/.test(k) && typeof v === "string").map(([, v]) => v as string));
    const memoryScopes = requests.filter(r => r.identityVerified && r.tool === "memory" && r.resource.startsWith("memory/")).map(r => ({ ownerId: r.actorId, key: r.resource.slice(7), ...(run?.finishedAt ? { createdAt: { lte: run.finishedAt } } : {}) }));
    const memories = await tx.memoryVersion.findMany({ where: { OR: [{ id: { in: memoryIds } }, ...memoryScopes] }, orderBy: [{ ownerId: "asc" }, { key: "asc" }, { version: "asc" }], take: 1001 });
    if (memories.length > 1000) throw new CapacityError("Memory evidence capacity exceeded");
    const eventIds = new Set(events.map(e => e.id));
    const experiment = run ? { id: run.id, scenario: run.scenario, scenarioVersion: run.scenarioVersion, mode: run.mode, actorId: run.actorId, sessionId: run.sessionId, status: run.status, startedAt: run.startedAt, finishedAt: run.finishedAt,
      budgets: run.budgets, configuration: run.configuration, results: { ...(run.results as Prisma.JsonObject), verifiedModelCalls: run.invocations.filter(invocationProof).length },
      observations: run.observations.map(o => ({ id: o.id, ordinal: o.ordinal, kind: o.kind, phase: o.phase, requestId: o.requestId, eventId: o.eventId, details: metadata(o.details), createdAt: o.createdAt })),
      invocations: run.invocations.map(i => ({ id: i.id, runId: i.runId, actorId: run.actorId, provider: i.provider, requestedModel: i.model, reportedModel: i.reportedModel, provenance: i.provenance, status: i.status, responseId: i.responseId, latencyMs: i.latencyMs, inputTokens: i.inputTokens, outputTokens: i.outputTokens, totalTokens: i.totalTokens, errorCode: i.errorCode, startedAt: i.startedAt, finishedAt: i.finishedAt, gatewayRequestIds: run.observations.filter(o => o.kind === "TOOL_REQUESTED" && (o.details as { invocationId?: string }).invocationId === i.id).flatMap(o => o.requestId ? [o.requestId] : []) })) } : null;
    return { experiment,
      events: events.map(e => ({ id: e.id, ordinal: e.ordinal, actorId: e.actorId, identityVerified: e.identityVerified, sessionId: e.sessionId, requestId: e.requestId, runId: e.runId, module: e.module, kind: e.kind, severity: e.severity, simulated: e.simulated, createdAt: e.createdAt, incidentId: e.incidentId, details: metadata(e.details), findings: e.findings.map(f => ({ id: f.id, module: f.module, rule: f.rule, explanation: safeText(f.explanation) })) })),
      decisions: requests.map(r => ({ requestId: r.id, actorId: r.actorId, identityVerified: r.identityVerified, sessionId: r.sessionId, tool: r.tool, operation: r.operation, resource: safeText(r.resource), sourceId: r.sourceId, simulated: r.simulated, allowed: r.allowed, reason: r.reason, createdAt: r.createdAt, execution: metadata(r.execution), decision: r.decision ? { id: r.decision.id, allowed: r.decision.allowed, rule: r.decision.rule, createdAt: r.decision.createdAt } : null, phase: run?.observations.find(o => o.requestId === r.id && o.kind === "TOOL_REQUESTED")?.phase ?? null,
        honeypotInteractions: interactions.filter(t => t.requestId === r.id).map(t => ({ id: t.id, trapId: t.trapId, category: t.trap.category, synthetic: true, actorId: t.actorId, sessionId: t.sessionId, operation: t.operation, eventId: t.eventId, incidentId: t.incidentId, createdAt: t.createdAt })) })),
      memory: memories.map(m => ({ id: m.id, ownerId: m.ownerId, key: m.key, version: m.version, parentId: m.parentId, contentHash: m.contentHash, sourceId: m.sourceId, sourceTrust: m.sourceTrust, sessionId: m.sessionId, authorization: safeText(m.authorization), protected: m.protected, restoredFromId: m.restoredFromId, createdAt: m.createdAt, integrityAtExport: verifySignature(m) ? "verified" : "tampered", verifiedAt: createdAt, contentOmitted: true })),
      incidents: incidents.map(i => ({ id: i.id, actorId: i.actorId, identityVerified: i.identityVerified, sessionId: i.sessionId, simulated: i.simulated, severity: i.severity, status: i.status, title: safeText(i.title), reasons: i.reasons, explanation: safeText(i.explanation), recommendation: safeText(i.recommendation), createdAt: i.createdAt, updatedAt: i.updatedAt, evidence: i.evidence.filter(e => eventIds.has(e.eventId)).map(e => ({ id: e.id, eventId: e.eventId })), scope: kind === "run" ? "Only evidence included in this experiment export" : "Complete persisted incident timeline", actions: i.actions.map(a => ({ id: a.id, actorId: a.actorId, action: a.action, reason: safeText(a.reason), operator: a.operator, createdAt: a.createdAt })) })),
      traps: interactions.map(t => ({ id: t.id, trapId: t.trapId, name: t.trap.name, category: t.trap.category, resource: t.trap.resource, synthetic: true, actorId: t.actorId, sessionId: t.sessionId, requestId: t.requestId, eventId: t.eventId, incidentId: t.incidentId, operation: t.operation, createdAt: t.createdAt })) };
  }, { timeout: 30000 }));
  // Explicit projection and final string redaction precede serialization and hashes.
  const sponsor=await sponsorEvidence(data.decisions.map(d=>d.requestId),data.decisions.flatMap(d=>d.sourceId?[d.sourceId]:[]));
  const sanitized = JSON.parse(JSON.stringify({...data,incidents:data.incidents.map(i=>({...i,sponsorEvidence:sponsor}))}, (_key, v) => typeof v === "string" ? safeText(v) : v)) as typeof data;
  const report = `<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>Ghost Ops forensic report</title><style>body{font:15px system-ui;max-width:1100px;margin:40px auto;padding:20px;color:#18252a}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #cbd2d5;text-align:left}code{overflow-wrap:anywhere}</style><h1>Ghost Ops forensic report</h1><h2>Executive summary</h2><p>${html(kind)} <code>${html(id)}</code>. This report describes persisted observations and policy results, not a verdict of malicious intent.</p><h2>Affected agent / provenance</h2><pre>${html(canonical(sanitized.experiment ? { actorId: sanitized.experiment.actorId, sessionId: sanitized.experiment.sessionId, mode: sanitized.experiment.mode, invocations: sanitized.experiment.invocations } : sanitized.incidents.map(i => ({ actorId: i.actorId, identityVerified: i.identityVerified, simulated: i.simulated }))))}</pre><h2>Timeline</h2><table><tr><th>Order/time</th><th>Engine / observation</th><th>Evidence</th></tr>${sanitized.events.map(e => `<tr id="event-${html(e.id)}"><td>${e.ordinal} / ${html(e.createdAt)}</td><td>${html(e.module)} / ${html(e.kind)}<br>${e.identityVerified ? "Verified attribution" : "Unverified claim"}</td><td><code>${html(e.id)}</code></td></tr>`).join("")}</table>${["AgentDNA", "ShadowWatch", "MemoryGuard", "GhostTrap"].map(module => `<h2>${html(module)} findings</h2><ul>${sanitized.events.filter(e => e.module === module).map(e => `<li><a href="#event-${html(e.id)}">${html(e.kind)} / ${html(e.id)}</a> ${e.findings.map(f => html(f.rule) + ": " + html(f.explanation)).join("; ")}</li>`).join("") || "<li>No matching persisted event in this scope.</li>"}</ul>`).join("")}<h2>Enforcement</h2><pre>${html(canonical(sanitized.decisions))}</pre><h2>Memory integrity at export</h2><pre>${html(canonical(sanitized.memory))}</pre><h2>Honeypot evidence</h2><pre>${html(canonical(sanitized.traps))}</pre><h2>Correlation and containment</h2><pre>${html(canonical(sanitized.incidents))}</pre><h2>Outcome</h2><pre>${html(canonical(sanitized.experiment?.results ?? sanitized.incidents.map(i => ({ id: i.id, status: i.status }))))}</pre><h2>Limitations</h2><p>Local synthetic environment only. No private reasoning, memory contents, raw tool outputs or credentials included. Hashes alone do not establish origin. Local HMAC assumes an uncompromised host/key and is not external attestation. Missing evidence is not fabricated; scripted probes are not model decisions. Integrity checks here describe export time, not proof of historical integrity.</p></html>`;
  const files = { "experiment.json": canonical(sanitized.experiment), "events.jsonl": sanitized.events.map(canonical).join("\n") + "\n", "policy-decisions.json": canonical(sanitized.decisions), "memory-evidence.json": canonical(sanitized.memory), "incidents.json": canonical(sanitized.incidents), "summary.html": report };
  const unsigned = { formatVersion: 1, packageId: randomUUID(), createdAt, scope: kind, subjectId: id, experimentIds: sanitized.experiment ? [sanitized.experiment.id] : [], incidentIds: sanitized.incidents.map(i => i.id), files: Object.entries(files).map(([name, value]) => ({ name, sha256: contentHash(value), bytes: Buffer.byteLength(value) })), limitations: ["Hashing is not proof of trustworthy origin", "HMAC authenticates only to the local host/key trust boundary", "Memory contents and raw model/tool outputs omitted", "Integrity verification is export-time validation", "No externally attested or tamper-proof claim"] };
  const manifest = { ...unsigned, authentication: { algorithm: "HMAC-SHA256", tag: manifestMac(canonical(unsigned)) } };
  const zip = evidenceZip({ ...files, "manifest.json": canonical(manifest) });
  const verification = verifyEvidence(zip, (text, tag) => secureEqual(manifestMac(text), tag));
  return { zip, manifest, verification };
}

async function exportHuntEvidence(id: string) {
  const createdAt = new Date().toISOString();
  const data = await serialized(() => db.$transaction(async tx => {
    const investigation = await tx.huntCase.findUniqueOrThrow({ where: { id } });
    const links = await tx.huntLink.findMany({ where: { caseId: id }, orderBy: { createdAt: "asc" }, take: 2001 });
    if (links.length > 2000) throw new CapacityError("Hunt evidence capacity exceeded; no truncated package");
    const plans = await tx.responsePlan.findMany({ where: { caseId: id }, take: 101 }); if (plans.length > 100) throw new CapacityError("Response export capacity");
    const planEvidence = plans.flatMap(p => p.evidenceIds as string[]);
    const verificationRequests = plans.flatMap(p => { const r = metadata(p.result); return typeof r.verificationRequestId === "string" ? [r.verificationRequestId] : []; });
    const events = await tx.securityEvent.findMany({ where: { OR: [{ id: { in: [...links.map(l => l.eventId), ...planEvidence] } }, { requestId: { in: verificationRequests } }] }, orderBy: { ordinal: "asc" }, take: 4001 }); if (events.length > 4000) throw new CapacityError("Hunt event export capacity");
    const requests = await tx.toolRequest.findMany({ where: { id: { in: events.flatMap(e => e.requestId ? [e.requestId] : []) } }, include: { decision: true }, orderBy: { createdAt: "asc" } });
    const memoryScopes = requests.filter(r => r.identityVerified && r.tool === "memory" && r.resource.startsWith("memory/")).map(r => ({ ownerId: r.actorId, key: r.resource.slice(7) }));
    const memories = await tx.memoryVersion.findMany({ where: { OR: [{ id: { in: links.filter(l => l.target.startsWith("memory:")).map(l => l.target.slice(7)) } }, ...memoryScopes] }, orderBy: [{ ownerId: "asc" }, { key: "asc" }, { version: "asc" }], take: 1001 }); if (memories.length > 1000) throw new CapacityError("Hunt memory export capacity");
    const scope = await tx.huntScope.findUniqueOrThrow({ where: { id: investigation.scopeId } });
    const actionIds = plans.flatMap(p => { const r = metadata(p.result); return typeof r.actionId === "string" ? [r.actionId] : []; });
    const actions = await tx.containmentAction.findMany({ where: { id: { in: actionIds } }, orderBy: { createdAt: "asc" } });
    const baselineIds = events.flatMap(e => { const d = metadata(e.details); return typeof d.baselineId === "string" ? [d.baselineId] : []; });
    const baselines = await tx.behaviorBaseline.findMany({ where: { id: { in: baselineIds } }, orderBy: [{ agentId: "asc" }, { version: "asc" }], take: 101 }); if (baselines.length > 100) throw new CapacityError("Baseline export capacity");
    const deployments = await tx.deceptionDeployment.findMany({ where: { scopeId: scope.id }, take: 101 }); if (deployments.length > 100) throw new CapacityError("Deployment export capacity");
    const traps = await tx.trapInteraction.findMany({ where: { requestId: { in: requests.map(r => r.id) } }, include: { trap: true } });
    const scopeRecord = { ...investigation, kind: "hunt-investigation", operatorGrouping: true, links, actions: actions.map(a => ({ id: a.id, actorId: a.actorId, action: a.action, incidentId: a.incidentId, reason: a.reason, operator: a.operator, createdAt: a.createdAt })), scope: { id: scope.id, mode: scope.mode, revision: scope.revision, agentIds: scope.agentIds, activationOrdinal: scope.activationOrdinal }, baselines: baselines.map(b => ({ id: b.id, agentId: b.agentId, version: b.version, requestIds: b.requestIds, profile: b.profile, learningWindow: b.learningWindow, evaluationWindow: b.evaluationWindow, createdAt: b.createdAt })), plans: plans.map(p => ({ id: p.id, caseId: p.caseId, scopeId: p.scopeId, actorId: p.actorId, sessionId: p.sessionId, revision: p.revision, mode: p.mode, action: p.action, evidenceIds: p.evidenceIds, status: p.status, result: p.result, createdAt: p.createdAt, expiresAt: p.expiresAt, executedAt: p.executedAt })), deployments, honeypotInteractions: traps.map(t => ({ id: t.id, trapId: t.trapId, resource: t.trap.resource, synthetic: true, actorId: t.actorId, sessionId: t.sessionId, requestId: t.requestId, eventId: t.eventId, operation: t.operation, createdAt: t.createdAt })), uncertainty: "Source context/submission does not prove intent, influence or successful poisoning. No private reasoning or model inference claimed." };
    return { events: events.map(e => ({ id: e.id, ordinal: e.ordinal, actorId: e.actorId, identityVerified: e.identityVerified, sessionId: e.sessionId, requestId: e.requestId, module: e.module, kind: e.kind, severity: e.severity, simulated: e.simulated, createdAt: e.createdAt, incidentId: e.incidentId, details: metadata(e.details) })), decisions: requests.map(r => ({ requestId: r.id, actorId: r.actorId, identityVerified: r.identityVerified, sessionId: r.sessionId, tool: r.tool, resource: r.resource, operation: r.operation, sourceId: r.sourceId, allowed: r.allowed, reason: r.reason, simulated: r.simulated, execution: metadata(r.execution), decision: r.decision, createdAt: r.createdAt })), memory: memories.map(m => ({ id: m.id, ownerId: m.ownerId, key: m.key, version: m.version, parentId: m.parentId, sourceId: m.sourceId, sourceTrust: m.sourceTrust, contentHash: m.contentHash, protected: m.protected, integrityAtExport: verifySignature(m) ? "verified" : "tampered", contentOmitted: true })), investigations: [scopeRecord] };
  }, { timeout: 30000 }));
  const sponsor=await sponsorEvidence(data.decisions.map(d=>d.requestId),data.decisions.flatMap(d=>d.sourceId?[d.sourceId]:[]));
  const safe = JSON.parse(JSON.stringify({...data,investigations:data.investigations.map(i=>({...i,sponsorEvidence:sponsor}))}, (_key, v) => typeof v === "string" ? safeText(v) : v)) as typeof data;
  const files = { "experiment.json": "null", "events.jsonl": safe.events.map(canonical).join("\n") + "\n", "policy-decisions.json": canonical(safe.decisions), "memory-evidence.json": canonical(safe.memory), "incidents.json": canonical(safe.investigations), "summary.html": `<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'"><title>Ghost Hunt evidence</title><h1>Ghost Hunt investigation</h1><p>${html(id)}. Explicit operator grouping; only recorded message references prove a submission relationship, never intent.</p><h2>Observed timeline</h2><ol>${safe.events.map(e => `<li>${e.ordinal} / ${html(e.createdAt)} / ${html(e.actorId)} / ${html(e.module)} / ${html(e.kind)} / evidence ${html(e.id)}</li>`).join("")}</ol><h2>Policy decisions</h2><pre>${html(canonical(safe.decisions))}</pre><h2>Memory verification</h2><pre>${html(canonical(safe.memory))}</pre><h2>Linked relationships / responses / uncertainty</h2><pre>${html(canonical(safe.investigations))}</pre><p>Real local tools; scripted decisions unless separate verified provider evidence exists. Local HMAC assumes an uncompromised host/key, not external attestation.</p></html>` };
  const unsigned = { formatVersion: 1, packageId: randomUUID(), createdAt, scope: "hunt", subjectId: id, experimentIds: [], incidentIds: [id], files: Object.entries(files).map(([name, value]) => ({ name, sha256: contentHash(value), bytes: Buffer.byteLength(value) })), limitations: ["Hunt-investigation record, not a fabricated legacy Incident", "Scope membership is operator grouping, not causality", "Submission/source context does not prove influence", "Local HMAC is not external attestation", "Raw content, credentials and reasoning omitted"] };
  const manifest = { ...unsigned, authentication: { algorithm: "HMAC-SHA256", tag: manifestMac(canonical(unsigned)) } };
  const zip = evidenceZip({ ...files, "manifest.json": canonical(manifest) });
  return { zip, manifest, verification: verifyEvidence(zip, (text, tag) => secureEqual(manifestMac(text), tag)) };
}
