import { randomUUID } from "node:crypto";
import { z } from "zod";
import {db} from "./db";
import {mac,secureEqual} from "./config";
import {verifySignature} from "./memory";
import {canonical} from "@/lib/canonical";
import {evidenceZip} from "@/lib/evidence-zip";
import {contentHash,verifyEvidence} from "@/lib/evidence-verification";
import {sentinelSnapshot} from "./sentinel";
import {ConflictError,CapacityError} from "./gateway";
function redact(s:string){let v=s;for(const key of [process.env.OPENAI_API_KEY,process.env.GHOSTOPS_GITHUB_TOKEN,process.env.GHOSTOPS_LOCAL_MODEL_KEY,process.env.GHOSTOPS_SIGNING_SECRET])if(key&&key.length>=8)v=v.replaceAll(key,"[REDACTED]");return v.replace(/Bearer\s+\S+|sk-[a-zA-Z0-9_-]{8,}|(?:api[_ -]?key|password|secret|credential)\s*[:=]\s*\S+/gi,"[REDACTED]");}
export async function exportSentinelEvidence(id:string){z.string().uuid().parse(id);const snapshot=await sentinelSnapshot(id),run=snapshot.runs.find(r=>r.id===id);if(!run||run.status==="running")throw new ConflictError("Terminal Sentinel run required");
  const agents=run.agentIds as string[];const requests=await db.toolRequest.findMany({where:{actorId:{in:agents}},include:{decision:true},orderBy:{createdAt:"asc"},take:201});if(requests.length>200)throw new CapacityError("No truncated Sentinel export");
  const events=await db.securityEvent.findMany({where:{actorId:{in:agents},identityVerified:true,simulated:false},orderBy:{ordinal:"asc"},take:1001});if(events.length>1000)throw new CapacityError("No truncated event export");
  const incidents=await db.incident.findMany({where:{actorId:{in:agents},identityVerified:true,simulated:false},include:{evidence:true,actions:true}});
  const memory=await db.memoryVersion.findMany({where:{ownerId:{in:agents}},orderBy:{version:"asc"}});
  const data={experiment:{id,kind:"web-sentinel",configuration:run.configuration,status:run.status,createdAt:run.createdAt,finishedAt:run.finishedAt,assessment:run.assessment,sponsors:run.sponsors,observations:run.observations.map(o=>{const result=(o.data as {result?:Record<string,unknown>}).result;return {...o,...(result?.advisories?{data:{...(o.data as object),result:{...result,advisories:(result.advisories as Record<string,unknown>[]).map(a=>Object.fromEntries(Object.entries(a).filter(([key])=>key!=="summary")))}}}:{})};}),publication:run.publication,limitations:["Local host/key HMAC is not external attestation","Public summaries omitted where metadata suffices","Model final observable output is not private reasoning","A source or scanner match is not proof of exploitability","No external action is claimed without actual read-back evidence"]},
    events:events.map(e=>({id:e.id,ordinal:e.ordinal,actorId:e.actorId,sessionId:e.sessionId,requestId:e.requestId,module:e.module,kind:e.kind,createdAt:e.createdAt,incidentId:e.incidentId,details:e.details})),
    decisions:requests.map(r=>({id:r.id,requestId:r.id,actorId:r.actorId,sessionId:r.sessionId,identityVerified:r.identityVerified,sourceId:r.sourceId,tool:r.tool,operation:r.operation,resource:r.resource,allowed:r.allowed,reason:r.reason,execution:r.execution,decision:r.decision,outputOmitted:true})),
    incidents:incidents.map(i=>({id:i.id,actorId:i.actorId,sessionId:i.sessionId,status:i.status,severity:i.severity,evidence:i.evidence,actions:i.actions})),
    memory:memory.map(m=>({id:m.id,ownerId:m.ownerId,key:m.key,version:m.version,parentId:m.parentId,sourceId:m.sourceId,sourceTrust:m.sourceTrust,contentHash:m.contentHash,protected:m.protected,integrityAtExport:verifySignature(m)?"verified":"tampered",contentOmitted:true}))};
  const safe=JSON.parse(JSON.stringify(data,(_key,v)=>typeof v==="string"?redact(v):v)) as typeof data;
  const html=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
  const files={"experiment.json":canonical(safe.experiment),"events.jsonl":safe.events.map(canonical).join("\n")+"\n","policy-decisions.json":canonical(safe.decisions),"memory-evidence.json":canonical(safe.memory),"incidents.json":canonical(safe.incidents),"summary.html":`<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'"><title>Web Sentinel evidence</title><h1>Web Sentinel research report</h1><p>${html(id)} / ${html(run.status)}. Actual persisted observations; no unsupported compromise conclusion.</p><h2>Challenge readiness</h2><pre>${html(canonical(run.assessment))}</pre><h2>Research, execution and publication provenance</h2><pre>${html(canonical(safe.experiment))}</pre><h2>Gateway decisions</h2><pre>${html(canonical(safe.decisions))}</pre><h2>Memory verification</h2><pre>${html(canonical(safe.memory))}</pre><h2>Investigation evidence</h2><pre>${html(canonical(safe.incidents))}</pre><p>SHA-256/HMAC assumes an uncompromised local host/signing key; not external attestation. Scripts/mocks never establish autonomous model or live sponsor execution.</p></html>`};
  const unsigned={formatVersion:1,packageId:randomUUID(),createdAt:new Date().toISOString(),scope:"sentinel",subjectId:id,experimentIds:[id],incidentIds:safe.incidents.map(i=>i.id),files:Object.entries(files).map(([name,value])=>({name,sha256:contentHash(value),bytes:Buffer.byteLength(value)})),limitations:safe.experiment.limitations};const tag=mac(`ghostops-evidence:v1:${canonical(unsigned)}`),manifest={...unsigned,authentication:{algorithm:"HMAC-SHA256",tag}};
  const zip=evidenceZip({...files,"manifest.json":canonical(manifest)});return {zip,manifest,verification:verifyEvidence(zip,(text,tag)=>secureEqual(mac(`ghostops-evidence:v1:${text}`),tag))};
}
