import { afterEach, expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { createServer, type Server } from "node:http";
import { GhostOpsClient, GhostOpsError, endpointOrigin, validateTool, decisionError } from "../packages/ghostops-sdk/src/index";
import { runOptionalModel } from "../examples/external-agent/src/model";
const identity = { agentId: "live-sdk-test", sessionId: randomUUID(), credential: "a".repeat(64) };
let server: Server | undefined;
afterEach(async () => { vi.restoreAllMocks(); if (server) { server.closeAllConnections(); await new Promise<void>(r => server!.close(() => r())); server = undefined; } });
it.each(["https://127.0.0.1:3210", "http://localhost:3210", "http://example.com", "http://127.0.0.1:3210/api/mcp", "http://user:secret@127.0.0.1:3210", "http://127.0.0.1:3210/?token=x"])("rejects an unapproved endpoint %s without network", endpoint => { expect(() => endpointOrigin(endpoint)).toThrow(GhostOpsError); });
it("keeps credential out of public serialization and validates configuration", () => { const c = new GhostOpsClient({ ...identity, endpoint: "http://127.0.0.1:3210" }); expect(JSON.stringify(c)).not.toContain(identity.credential); expect(() => new GhostOpsClient({ ...identity, credential: "invalid", endpoint: "http://127.0.0.1:3210" })).toThrow(GhostOpsError); expect(() => new GhostOpsClient({ ...identity, endpoint: "http://127.0.0.1:3210", timeoutMs: 30001 })).toThrow(GhostOpsError); });
it.each([
  ["shell", { resource: "docs/research" }], ["read_document", { resource: "../secret" }], ["read_memory", { resource: "memory/runtime-notes", ownerId: "victim" }], ["read_document", { resource: "docs/research", actorId: "victim" }], ["write_summary", { resource: "research/summary" }], ["write_memory", { resource: "memory/runtime-notes", content: "x".repeat(4001) }], ["read_document", { resource: "infra/status" }], ["read_document", { resource: "docs/research", content: "unexpected" }]
])("rejects unsupported, forged or invalid arguments for %s", (name, args) => { expect(() => validateTool(name, { ...args, requestId: randomUUID() })).toThrow(GhostOpsError); });
it.each([["AGENT_QUARANTINED", "AGENT_QUARANTINED"], ["CREDENTIAL_REVOKED", "CREDENTIAL_REVOKED"], ["INVALID_CREDENTIAL", "AUTHENTICATION_FAILED"], ["RESOURCE_NOT_PERMITTED", "PERMISSION_DENIED"], ["TOOL_HANDLER_FAILED", "TOOL_FAILED"]])("maps denied %s to stable safe errors", (reason, code) => { const e = decisionError({ requestId: randomUUID(), allowed: false, reason, output: null, incidentId: null, replayed: false }); expect(e.code).toBe(code); expect(e.toJSON().reason).toBe(reason); });
async function fake(handler: (message: Record<string, unknown>) => unknown, status = 200, slow = false) {
  server = createServer(async (req, res) => {
    let body = ""; for await (const chunk of req) body += chunk; const message = JSON.parse(body || "{}");
    if (slow) return;
    if (message.method === "notifications/initialized") { res.writeHead(202); res.end(); return; }
    res.writeHead(status, { "content-type": "application/json" }); res.end(JSON.stringify(status === 200 ? { jsonrpc: "2.0", id: message.id, result: handler(message) } : { error: "Untrusted diagnostic aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }));
  }); await new Promise<void>(r => server!.listen(0, "127.0.0.1", r)); const port = (server.address() as { port: number }).port; return `http://127.0.0.1:${port}`;
}
const initialize = { protocolVersion: "2025-11-25", serverInfo: { name: "fixture", version: "1" }, capabilities: { tools: {} } };
it("initializes MCP, discovers tools, returns denied evidence and logs metadata only", async () => {
  const logger = vi.fn(), id = randomUUID(), endpoint = await fake(m => m.method === "initialize" ? initialize : m.method === "tools/list" ? { tools: [{ name: "read_document", inputSchema: { type: "object" } }] } : { content: [], isError: true, structuredContent: { requestId: id, allowed: false, reason: "RESOURCE_NOT_PERMITTED", output: null, incidentId: null, replayed: false } });
  const client = new GhostOpsClient({ ...identity, endpoint, logger }); try { expect((await client.listTools())[0].name).toBe("read_document"); const d = await client.requestTool({ tool: "read_document", arguments: { requestId: id, resource: "docs/research" } }); expect(d.allowed).toBe(false); await expect(client.callTool({ tool: "read_document", arguments: { requestId: id, resource: "docs/research" } })).rejects.toMatchObject({ code: "PERMISSION_DENIED" }); expect(JSON.stringify(logger.mock.calls)).not.toContain(identity.credential); } finally { await client.close(); }
});
it("does not retry failed authentication or disclose raw gateway errors", async () => { const endpoint = await fake(() => ({}), 401), client = new GhostOpsClient({ ...identity, endpoint }); await expect(client.connect()).rejects.toMatchObject({ code: "AUTHENTICATION_FAILED" }); await client.close(); });
it("handles gateway connection failure without a fallback", async () => { const endpoint = await fake(() => ({}), 503), client = new GhostOpsClient({ ...identity, endpoint }); await expect(client.connect()).rejects.toMatchObject({ code: "GATEWAY_UNAVAILABLE" }); await client.close(); });
it("times out and respects pre-cancelled calls", async () => { const endpoint = await fake(() => ({}), 200, true), client = new GhostOpsClient({ ...identity, endpoint, timeoutMs: 25 }); await expect(client.connect()).rejects.toMatchObject({ code: "REQUEST_TIMEOUT" }); const controller = new AbortController(); controller.abort(); await expect(client.connect({ signal: controller.signal })).rejects.toMatchObject({ code: "CANCELLED" }); await client.close(); });
it("rejects forged/mismatched response receipts", async () => { const endpoint = await fake(m => m.method === "initialize" ? initialize : { content: [], structuredContent: { requestId: randomUUID(), allowed: true, reason: "AUTHORIZED", output: "fake", incidentId: null, replayed: false, verifiedProvider: true } }), client = new GhostOpsClient({ ...identity, endpoint }); try { await expect(client.requestTool({ tool: "read_document", arguments: { resource: "docs/research" } })).rejects.toMatchObject({ code: "INVALID_REQUEST" }); } finally { await client.close(); } });
it("retains the request UUID on uncertain failed delivery", async () => { const endpoint = await fake(() => ({}), 503), client = new GhostOpsClient({ ...identity, endpoint }), requestId = randomUUID(); await expect(client.requestTool({ tool: "write_summary", arguments: { requestId, resource: "research/summary", content: "Synthetic summary" } })).rejects.toMatchObject({ code: "GATEWAY_UNAVAILABLE", requestId }); await client.close(); });
it("bounds oversized gateway error bodies before parsing", async () => { const endpoint = await fake(() => ({ oversized: "x".repeat(70000) })), client = new GhostOpsClient({ ...identity, endpoint }); await expect(client.connect()).rejects.toMatchObject({ code: "INVALID_REQUEST" }); await client.close(); });
it("never executes the optional model adapter without interactive opt-in", async () => { const call = vi.fn(); await expect(runOptionalModel(call, false)).rejects.toThrow(/interactive/); expect(call).not.toHaveBeenCalled(); });
it("blocks optional external inference in the automated test environment", async () => { const call = vi.fn(); await expect(runOptionalModel(call, true)).rejects.toThrow(/interactive/); expect(call).not.toHaveBeenCalled(); });
