// @vitest-environment happy-dom
// Nonvisual component contract tests. React Flow is a mocked interaction boundary,
// records/commands are genuine backend logic; this is NOT visual or pointer QA.
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { randomUUID, randomBytes } from "node:crypto";
import { render, screen, fireEvent, waitFor, cleanup } from "@testing-library/react";
import type { Node, Edge } from "@xyflow/react";
import ThreatHunt from "../src/components/workspace/threat-hunt";
import { huntCommand, huntSnapshot } from "../src/server/hunt";
import { callRuntime, enrollRuntime, rotateRuntime } from "../src/server/runtime";
import { huntGraph } from "../src/lib/hunt-graph";
import { integrationSchema } from "../src/lib/runtime-contract";
import { snapshot } from "../src/server/service";
import { defaultLayout } from "../src/lib/workspace-model";
import type { State } from "../src/lib/view-types";
vi.mock("@xyflow/react", () => ({ Position: { Left: "left", Right: "right" }, Handle: () => null, Background: () => null, Controls: () => null,
  ReactFlow: ({ nodes, edges, onNodeClick, onEdgeClick }: { nodes: Node<{ label: string }>[]; edges: Edge[]; onNodeClick: (event: null, node: Node) => void; onEdgeClick: (event: null, edge: Edge) => void }) => <div aria-label="Mocked graph interaction boundary">{nodes.map(n => <button key={n.id} data-position={JSON.stringify(n.position)} onClick={() => onNodeClick(null, n)}>Entity {n.data.label}</button>)}{edges.map(e => <button key={e.id} onClick={() => onEdgeClick(null, e)}>Evidence {e.id}</button>)}</div>
}));
let identity: { actorId: string; sessionId: string; credential: string }, scopeId: string, state: State;
beforeEach(async () => { const credential = randomBytes(32).toString("hex"); const actorId = `live-hunt-ui-${randomUUID().slice(0, 8)}`; identity = { ...await enrollRuntime({ commandId: randomUUID(), actorId, credential, integration: integrationSchema.parse({ name: "Hunt component agent", role: "research", permissions: { tools: ["documents:read", "documents:ingest", "summarize:write", "memory:read", "memory:write"], resources: ["docs/research", "docs/untrusted", "research/summary", "memory/runtime-policy", "memory/runtime-notes"], destinations: [] } }) }) as { actorId: string; sessionId: string }, credential }; const scope = await huntCommand({ commandId: randomUUID(), action: "scope", name: "Component fixture", agentIds: [actorId] }) as { id: string }; scopeId = scope.id; await callRuntime(actorId, identity.sessionId, credential, "restricted_admin", { requestId: randomUUID(), resource: "decoy/admin" }); state = JSON.parse(JSON.stringify(await snapshot())); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
async function mount(fail = false) { const fetcher = vi.fn(async (_url: string, options?: RequestInit) => { if (options?.method === "POST") { if (fail) throw new Error("Transport interrupted; delivery uncertain"); return new Response(JSON.stringify(await huntCommand(JSON.parse(options.body as string)))); } return new Response(JSON.stringify(await huntSnapshot())); }); vi.stubGlobal("fetch", fetcher); const navigate = vi.fn(), dispatch = vi.fn(); render(<ThreatHunt state={state} csrf="fixture-csrf" layout={defaultLayout({ width: 1440, height: 900 })} dispatch={dispatch} navigate={navigate} />); await waitFor(() => expect(screen.getByText(/evidence-linked policy violations/)).toBeTruthy()); fireEvent.change(screen.getByLabelText("Hunt investigation"), { target: { value: (await huntSnapshot()).cases.find(c => c.scopeId === scopeId)!.id } }); return { fetcher, navigate, dispatch }; }
it("actual agent and event selection navigate existing records without mutating policy", async () => { const { fetcher, navigate } = await mount(); fireEvent.click(screen.getByRole("button", { name: `Entity ${state.agents.find(a => a.id === identity.actorId)!.name}` })); expect(navigate).toHaveBeenCalledWith("Agent inspector", identity.actorId); fireEvent.click(screen.getAllByRole("button", { name: /^Evidence / })[0]); expect(screen.getByText(/Graph highlighting uses selected event/)).toBeTruthy(); fireEvent.change(screen.getByLabelText("Hunt evidence category"), { target: { value: "confirmed-violation" } }); fireEvent.click(screen.getByRole("button", { name: "Pause display updates" })); expect(fetcher.mock.calls.every(c => c[1]?.method !== "POST")).toBe(true); });
it("automatic scope changes need an explicit checkbox and retain configured limits", async () => { await huntCommand({ commandId: randomUUID(), action: "configure", scopeId, mode: "OBSERVE", learningWindow: 12, evaluationWindow: 4, maxActionsPerHour: 1 }); const { fetcher } = await mount(); const button = screen.getByRole<HTMLButtonElement>("button", { name: "Enable scoped AUTOMATIC" }); expect(button.disabled).toBe(true); fireEvent.click(screen.getByLabelText(/I explicitly authorize bounded automatic quarantine/)); fireEvent.click(button); await waitFor(() => expect(fetcher.mock.calls.some(c => c[1]?.method === "POST")).toBe(true)); const options = fetcher.mock.calls.find(c => c[1]?.method === "POST")![1]!; expect(options.headers).toMatchObject({ "x-ghostops-csrf": "fixture-csrf" }); expect(JSON.parse(options.body as string)).toMatchObject({ mode: "AUTOMATIC", learningWindow: 12, evaluationWindow: 4, maxActionsPerHour: 1, commandId: expect.any(String) }); });
it("uncertain command delivery retries the exact idempotency ID, not a new response", async () => { const { fetcher } = await mount(true); fireEvent.click(screen.getAllByRole("button", { name: /^Preview response/ })[0]); await waitFor(() => expect(screen.getByText(/Uncertain delivery/)).toBeTruthy()); fireEvent.click(screen.getByRole("button", { name: "Retry exact command" })); await waitFor(() => expect(fetcher.mock.calls.filter(c => c[1]?.method === "POST")).toHaveLength(2)); const calls = fetcher.mock.calls.filter(c => c[1]?.method === "POST"); expect(calls[0][1]!.body).toEqual(calls[1][1]!.body); });
it("neighborhood exploration positions older nodes outside the initial bounded sample", async () => {
  const credential = randomBytes(32).toString("hex"); identity = { ...identity, ...await rotateRuntime({ commandId: randomUUID(), actorId: identity.actorId, credential, restore: false }) as { sessionId: string }, credential };
  for (let n = 0; n < 4; n++) await callRuntime(identity.actorId, identity.sessionId, credential, "read_document", { requestId: randomUUID(), resource: "docs/research" });
  await huntCommand({ commandId: randomUUID(), action: "baseline", scopeId, actorId: identity.actorId });
  for (let n = 0; n < 18; n++) await callRuntime(identity.actorId, identity.sessionId, credential, "read_memory", { requestId: randomUUID(), resource: "memory/runtime-notes" });
  state = JSON.parse(JSON.stringify(await snapshot())); const data = await huntSnapshot(); const c = data.cases.find(c => c.scopeId === scopeId)!; const visible = new Set(huntGraph(data.links, c.id).nodes.map(n => n.entity)); const hidden = data.links.find(l => l.caseId === c.id && l.target.startsWith("finding:") && !visible.has(l.target)); expect(hidden).toBeTruthy(); await mount(); fireEvent.change(screen.getByLabelText("Hunt neighborhood"), { target: { value: hidden!.target } }); const button = screen.getByRole("button", { name: `Entity ${hidden!.target.slice(8)}` }); expect(JSON.parse(button.getAttribute("data-position")!)).not.toEqual({ x: 0, y: 0 });
});
