// Adapter contracts with fake services. No actual ClickHouse/MongoDB verification.
import {beforeEach,expect,it,vi} from "vitest";
import {randomUUID} from "node:crypto";
const fake=vi.hoisted(()=>({command:vi.fn(),insert:vi.fn(),query:vi.fn(),close:vi.fn(),createIndex:vi.fn(),updateOne:vi.fn(),find:vi.fn(),connect:vi.fn(),rows:[] as unknown[]}));
vi.mock("@clickhouse/client",()=>({createClient:()=>({command:fake.command,insert:fake.insert,query:fake.query,close:fake.close})}));
vi.mock("mongodb",()=>({MongoClient:class{connect=fake.connect;close=fake.close;db(){return {collection:()=>({createIndex:fake.createIndex,updateOne:fake.updateOne,find:fake.find})};}}}));
import {clickHouseOperation,mongoOperation,telemetryProjection,intelligenceProjection,reconcileIntelligenceHit} from "../src/server/sponsor-adapters";
beforeEach(()=>{vi.clearAllMocks();fake.rows=[];fake.query.mockResolvedValue({json:async()=>fake.rows});fake.find.mockImplementation(()=>({sort:()=>({limit:()=>({toArray:async()=>fake.rows})})}));});
it("ClickHouse inserts a bounded projection and uses source-scoped FINAL aggregation",async()=>{const e={id:randomUUID(),ordinal:1,createdAt:new Date(),actorId:"live-a",sessionId:null,requestId:null,identityVerified:false,module:"Gateway",kind:"TEST",simulated:false,incidentId:null};const rows=[telemetryProjection("source-a",e)];await clickHouseOperation("http://127.0.0.1:8123","restricted","synthetic-only","source-a",rows);expect(fake.insert).toHaveBeenCalledWith({table:"ghostops_events",values:rows,format:"JSONEachRow"});expect(fake.query.mock.calls[0][0].query).toContain("FINAL WHERE startsWith");expect(fake.query.mock.calls[0][0].query_params.prefix).toBe("source-a:");expect(fake.close).toHaveBeenCalledOnce();});
it("ClickHouse connection failure does not report a successful delivery",async()=>{fake.query.mockRejectedValueOnce(new Error("Fixture transport failure"));await expect(clickHouseOperation("http://127.0.0.1:8123","restricted","synthetic-only","source-a")).rejects.toThrow();expect(fake.close).toHaveBeenCalledOnce();});
it("unexpected analytics result shapes are rejected rather than stored",async()=>{fake.rows=[{arbitrarySecret:"not-allowed"}];await expect(clickHouseOperation("http://127.0.0.1:8123","restricted","synthetic-only","source-a")).rejects.toThrow();});
it("Mongo uses stable source-qualified upserts and literal bounded search",async()=>{const id=randomUUID(),doc=intelligenceProjection("source-a",{id,actorId:"live-a",identityVerified:true,severity:"high",status:"open",updatedAt:new Date()},[{id:randomUUID()}],[]);fake.rows=[doc];const result=await mongoOperation("mongodb://127.0.0.1:27017","source-a",[doc],"a.*");expect(fake.updateOne).toHaveBeenCalledWith({_id:doc._id},{$set:doc},{upsert:true});expect(fake.find.mock.calls[0][0].sourceNamespace).toBe("source-a");expect(fake.find.mock.calls[0][0].$or[0].summary.$regex).toBe("a\\.\\*");expect(result[0].sourceId).toBe(id);expect(result[0].evidenceIds).toEqual(doc.evidenceIds);expect(fake.close).toHaveBeenCalledOnce();});
it("Mongo refuses a returned cross-instance source",async()=>{fake.rows=[{_id:`foreign:${randomUUID()}`,sourceId:randomUUID(),agentId:null,summary:"Synthetic",evidenceIds:[],updatedAt:new Date().toISOString()}];await expect(mongoOperation("mongodb://127.0.0.1:27017","source-a")).rejects.toThrow("namespace mismatch");});
it("remote search metadata cannot replace SQLite authenticated identity or invent evidence",()=>{const id=randomUUID(),eventId=randomUUID(),row={_id:`source:${id}`,sourceId:id,agentId:"forged-agent",summary:"Invented narrative",evidenceIds:[eventId],updatedAt:new Date().toISOString(),provenance:"mongodb-index"};const incident={id,actorId:"verified-agent",identityVerified:true,events:[{id:eventId}]};expect(reconcileIntelligenceHit(row,incident).agentId).toBe("verified-agent");expect(reconcileIntelligenceHit(row,{...incident,identityVerified:false}).agentId).toBeNull();expect(()=>reconcileIntelligenceHit({...row,evidenceIds:[randomUUID()]},incident)).toThrow("source mismatch");});
