// @vitest-environment happy-dom
// Component behavior only. No browser screenshot or external service claim.
import {afterEach,expect,it,vi} from "vitest";
import {cleanup,render,screen,fireEvent,waitFor} from "@testing-library/react";
import SponsorIntegrations from "../src/components/workspace/sponsor-integrations";
import {sponsorSnapshot,sponsorPreflight,sponsorExecute} from "../src/server/sponsors";
import {defaultLayout,parsePreferences} from "../src/lib/workspace-model";
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it("preserves fifteen-window preferences and parks the new sponsor tool",()=>{const b={width:1440,height:900},p=defaultLayout(b);const older={...p,windows:p.windows.filter(w=>w.id!=="sponsors"&&w.id!=="sentinel")};const restored=parsePreferences(JSON.stringify(older),b);expect(restored.windows).toHaveLength(17);expect(restored.windows.find(w=>w.id==="sponsors")?.open).toBe(false);expect(restored.windows.find(w=>w.id==="network")).toEqual(older.windows.find(w=>w.id==="network"));});
it("opening the sponsor panel performs no paid or state-changing request",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(await sponsorSnapshot())));vi.stubGlobal("fetch",fetcher);render(<SponsorIntegrations csrf="test" navigate={vi.fn()}/>);await waitFor(()=>expect(screen.getByText(/Senso · CONFIGURATION REQUIRED/)).toBeTruthy());expect(fetcher.mock.calls).toHaveLength(1);});
it("editing an inspected form invalidates its execution confirmation",async()=>{vi.stubGlobal("fetch",async(url:string,options?:RequestInit)=>new Response(JSON.stringify(options?.method==="POST"?await sponsorPreflight(JSON.parse(options.body as string)):await sponsorSnapshot())));render(<SponsorIntegrations csrf="test" navigate={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Inspect exact action"}));await waitFor(()=>expect(screen.getByRole("button",{name:/Confirm inspected action/})).toBeTruthy());fireEvent.change(screen.getByLabelText("Approved target"),{target:{value:"corrected"}});expect(screen.queryByRole("button",{name:/Confirm inspected action/})).toBeNull();});
it("context fixture requires inspected confirmation and returns honest provenance",async()=>{const calls:{url:string;input:Record<string,unknown>}[]=[];vi.stubGlobal("fetch",async(url:string,options?:RequestInit)=>{if(options?.method==="POST"){const input=JSON.parse(options.body as string);calls.push({url,input});return new Response(JSON.stringify(url.endsWith("preflight")?await sponsorPreflight(input):await sponsorExecute(input)));}return new Response(JSON.stringify(await sponsorSnapshot()));});render(<SponsorIntegrations csrf="test" navigate={vi.fn()}/>);fireEvent.change(screen.getByLabelText("Action"),{target:{value:"context"}});fireEvent.click(screen.getByRole("button",{name:"Inspect exact action"}));await waitFor(()=>expect(screen.getByRole("button",{name:/Confirm inspected action/})).toBeTruthy());expect(calls).toHaveLength(1);fireEvent.click(screen.getByRole("button",{name:/Confirm inspected action/}));await waitFor(()=>expect(screen.getByText("Actual action receipt")).toBeTruthy());expect(calls[1].input.commandId).toBe(calls[0].input.commandId);expect(calls[1].input.fixture).toBe(true);expect(screen.getAllByText(/"provenance": "local-fixture"/).length).toBeGreaterThan(0);});
