// @vitest-environment happy-dom
// Synthetic DOM interaction tests, not browser screenshots or viewport visual verification.
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { useReducer } from "react";
import { randomUUID } from "node:crypto";
import { command, snapshot } from "../src/server/service";
import type { State } from "../src/lib/view-types";
import type { Entity } from "../src/lib/workspace-graph";
import { defaultLayout, storageKey, workspaceReducer } from "../src/lib/workspace-model";
import { WorkWindow } from "../src/components/workspace/window";
import { Workspace } from "../src/components/workspace/workspace";
import { EventTerminal } from "../src/components/workspace/event-terminal";
import { EvidenceInspector } from "../src/components/workspace/inspectors";
import AgentGraph from "../src/components/workspace/network";
import { MemoryDiff } from "../src/components/memory-diff";

// Only the Next lazy-loading boundary is stubbed in shell tests. The real React Flow
// component is tested separately below; backend snapshots are generated by real logic.
vi.mock("next/dynamic", () => ({ default: () => function GraphBoundary({ state, select }: { state: State; select: (entity: Entity) => void }) {
  return <button onClick={() => select({ kind: "agent", id: state.agents[0].id })}>Inspect graph agent</button>;
} }));

let state: State, compact = false;
beforeAll(async () => {
  await command({ commandId: randomUUID(), action: "reset" });
  await command({ commandId: randomUUID(), action: "compromise" });
  state = JSON.parse(JSON.stringify(await snapshot())) as State;
});
beforeEach(() => {
  localStorage.clear(); compact = false;
  vi.stubGlobal("matchMedia", (query: string) => ({ matches: query.includes("max-width") ? compact : false, media: query, addEventListener: () => {}, removeEventListener: () => {} }));
  vi.stubGlobal("ResizeObserver", class { constructor(private callback: ResizeObserverCallback) {} observe(target: Element) { queueMicrotask(() => this.callback([{ target, contentRect: { width: compact ? 390 : 1280, height: 760 } } as ResizeObserverEntry], this as unknown as ResizeObserver)); } unobserve() {} disconnect() {} });
  Object.defineProperty(HTMLElement.prototype, "setPointerCapture", { configurable: true, value: () => {} });
  Object.defineProperty(HTMLElement.prototype, "releasePointerCapture", { configurable: true, value: () => {} });
});
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });

function WindowHarness() {
  const [layout, dispatch] = useReducer(workspaceReducer, defaultLayout({ width: 1200, height: 700 }));
  const win = layout.windows[0];
  return <><WorkWindow window={win} bounds={layout.bounds} active mobile={false} dispatch={dispatch}><button>Content button</button><p>Select text without dragging</p></WorkWindow><output data-testid="geometry">{JSON.stringify(win)}</output></>;
}
const workspace = () => <Workspace state={state} connected busy={false} control={async () => null} result={null} setResult={() => {}} />;
function GraphHarness() {
  const [layout, dispatch] = useReducer(workspaceReducer, defaultLayout({ width: 1280, height: 760 }));
  return <><AgentGraph state={state} layout={layout} dispatch={dispatch} select={() => {}} /><output data-testid="positions">{JSON.stringify(layout.positions)}</output></>;
}
describe("actual window controls and geometry", () => {
  it("moves by pointer title-bar gesture and clamps the final committed geometry", () => {
    render(<WindowHarness />);
    const title = screen.getByLabelText(/Agent network title bar/);
    fireEvent.pointerDown(title, { pointerId: 1, button: 0, clientX: 10, clientY: 10 });
    fireEvent.pointerMove(title, { pointerId: 1, clientX: 2000, clientY: 2000 });
    fireEvent.pointerUp(title, { pointerId: 1 });
    const rect = JSON.parse(screen.getByTestId("geometry").textContent!);
    expect(rect.x + rect.width).toBe(1200); expect(rect.y + rect.height).toBe(700);
  });
  it("resizes via a real corner handler and supports non-drag keyboard resize", () => {
    const { container } = render(<WindowHarness />);
    const handle = container.querySelector(".resize-se")!;
    fireEvent.pointerDown(handle, { pointerId: 2, button: 0, clientX: 10, clientY: 10 });
    fireEvent.pointerMove(handle, { pointerId: 2, clientX: -2000, clientY: -2000 }); fireEvent.pointerUp(handle, { pointerId: 2 });
    expect(JSON.parse(screen.getByTestId("geometry").textContent!).width).toBe(340);
    fireEvent.keyDown(screen.getByLabelText(/Agent network title bar/), { altKey: true, shiftKey: true, key: "ArrowRight" });
    expect(JSON.parse(screen.getByTestId("geometry").textContent!).width).toBe(360);
  });
  it("does not start a drag from window controls or content", () => {
    render(<WindowHarness />);
    const before = JSON.parse(screen.getByTestId("geometry").textContent!);
    fireEvent.pointerDown(screen.getByText("Content button"), { pointerId: 3, button: 0, clientX: 10, clientY: 10 });
    fireEvent.pointerMove(screen.getByText("Content button"), { pointerId: 3, clientX: 500, clientY: 500 });
    expect(JSON.parse(screen.getByTestId("geometry").textContent!).x).toBe(before.x);
    fireEvent.click(screen.getByLabelText("Maximize Agent network"));
    expect(screen.getByLabelText("Restore Agent network")).toBeTruthy();
    fireEvent.click(screen.getByLabelText("Restore Agent network"));
    expect(JSON.parse(screen.getByTestId("geometry").textContent!).width).toBe(before.width);
  });
  it("docks from real title controls and preserves normal maximize/restore", () => {
    render(<WindowHarness />);
    fireEvent.click(screen.getByLabelText("Dock Agent network right"));
    expect(JSON.parse(screen.getByTestId("geometry").textContent!)).toMatchObject({ x: 600, y: 0, width: 600, height: 700 });
    fireEvent.click(screen.getByLabelText("Maximize Agent network")); fireEvent.click(screen.getByLabelText("Restore Agent network"));
    expect(JSON.parse(screen.getByTestId("geometry").textContent!).x).toBe(600);
  });
});
describe("workspace navigation and persistence", () => {
  it("opens and focuses tools, minimizes, reopens, and persists a validated arrangement", async () => {
    const first = render(workspace());
    await waitFor(() => expect(screen.getByLabelText("Agent network")).toBeTruthy());
    fireEvent.click(screen.getByLabelText("Open AgentDNA"));
    const dna = screen.getByLabelText("AgentDNA");
    expect(dna.className).toContain("focused");
    fireEvent.click(screen.getByLabelText("Minimize AgentDNA"));
    expect(screen.queryByLabelText("AgentDNA")).toBeNull();
    fireEvent.click(screen.getByLabelText("Restore AgentDNA"));
    expect(screen.getByLabelText("AgentDNA")).toBeTruthy();
    fireEvent.keyDown(screen.getByLabelText(/AgentDNA title bar/), { altKey: true, key: "ArrowRight" });
    await waitFor(() => expect(JSON.parse(localStorage.getItem(storageKey)!).windows.find((w: { id: string }) => w.id === "dna").open).toBe(true));
    const saved = localStorage.getItem(storageKey)!;
    first.unmount(); render(workspace());
    await waitFor(() => expect(screen.getByLabelText("AgentDNA")).toBeTruthy());
    expect(localStorage.getItem(storageKey)).toBe(saved);
  });
  it("switches presets and resets only presentation, without issuing security mutations", async () => {
    const control = vi.fn(async () => null);
    render(<Workspace state={state} busy={false} connected control={control} result={null} setResult={() => {}} />);
    await waitFor(() => expect(localStorage.getItem(storageKey)).not.toBeNull());
    fireEvent.click(screen.getByText("Incident Room"));
    await waitFor(() => expect(screen.getByLabelText("Investigations")).toBeTruthy());
    expect(screen.getByLabelText("MemoryGuard")).toBeTruthy();
    fireEvent.click(screen.getByTitle("Reset layout and node positions; backend data unchanged"));
    expect(screen.queryByLabelText("Investigations")).toBeNull(); expect(screen.getByLabelText("Agent network")).toBeTruthy(); expect(control).not.toHaveBeenCalled();
  });
  it("provides graph-to-agent inspection and opens evidence without losing the network", async () => {
    render(workspace());
    fireEvent.click(screen.getByText("Inspect graph agent"));
    const inspector = screen.getByLabelText("Agent inspector");
    expect(within(inspector).getByRole("heading", { name: state.agents[0].name })).toBeTruthy();
    const eventButton = inspector.querySelector<HTMLButtonElement>(".inspector-event")!;
    fireEvent.click(eventButton);
    expect(screen.getByLabelText("Evidence inspector")).toBeTruthy(); expect(screen.getByLabelText("Agent network")).toBeTruthy();
  });
  it("focuses the selected case and opens its persisted timeline event in a floating inspector", async () => {
    render(workspace());
    await waitFor(() => expect(localStorage.getItem(storageKey)).not.toBeNull());
    fireEvent.click(screen.getByText("Incident Room"));
    const selected = state.incidents.find(i => i.severity === "critical")!;
    fireEvent.change(screen.getByLabelText("Select investigation"), { target: { value: selected.id } });
    expect((screen.getByLabelText("Focus network investigation") as HTMLSelectElement).value).toBe(selected.id);
    const caseWindow = screen.getByLabelText("Investigations");
    const event = selected.events[0];
    fireEvent.click(within(caseWindow).getByText(event.message, { selector: ".case-event-body>span" }));
    expect(within(screen.getByLabelText("Evidence inspector")).getByText(event.kind, { selector: "h3" })).toBeTruthy();
    expect(screen.getByLabelText("MemoryGuard")).toBeTruthy();
  });
  it("allows keyboard launcher and non-drag mobile access to every tool", async () => {
    compact = true;
    render(workspace());
    await waitFor(() => expect(document.querySelectorAll(".work-window")).toHaveLength(1));
    for (const tool of ["dna", "shadow", "memory", "traps", "runtime", "demo"]) {
      fireEvent.change(screen.getByLabelText("Mobile active tool"), { target: { value: tool } });
      expect(document.querySelectorAll(".work-window")).toHaveLength(1);
      expect(document.querySelector(".work-window")!.getAttribute("data-window")).toBe(tool);
      expect(document.querySelector(".resize-handle")).toBeNull();
    }
    fireEvent.keyDown(window, { ctrlKey: true, key: "k" }); expect(screen.getByLabelText("Tool launcher")).toBeTruthy();
    fireEvent.keyDown(window, { key: "Escape" }); expect(screen.queryByLabelText("Tool launcher")).toBeNull();
    await waitFor(() => expect(JSON.parse(localStorage.getItem(storageKey)!).bounds.width).toBe(1280));
  });
  it("starts network-first and opens concise inspector tabs without security mutations", async () => {
    const control = vi.fn(async () => null);
    render(<Workspace state={state} busy={false} connected control={control} result={null} setResult={() => {}} />);
    await waitFor(() => expect(localStorage.getItem(storageKey)).not.toBeNull());
    expect(screen.getAllByLabelText("Agent inspector")).toHaveLength(1);
    fireEvent.click(screen.getByLabelText("Expand tool navigation"));
    expect(document.querySelector(".navigation-expanded")).toBeTruthy();
    fireEvent.click(screen.getByText("Inspect graph agent"));
    const tabs = screen.getByLabelText("Agent inspection sections");
    fireEvent.click(within(tabs).getByText("Permissions")); expect(screen.getByText("Granted capabilities")).toBeTruthy();
    fireEvent.click(within(tabs).getByText("Events")); expect(screen.getByText("Recent verified observations")).toBeTruthy();
    fireEvent.click(within(tabs).getByText("Memory")); expect(screen.getByText("Latest memory integrity")).toBeTruthy();
    expect(control).not.toHaveBeenCalled();
  });
});
describe("terminal, forensic evidence and actual React Flow", () => {
  it("pauses only display updates, resumes actual records and supports search/provenance filters", () => {
    const inspect = vi.fn();
    const { rerender } = render(<EventTerminal state={state} inspect={inspect} />);
    fireEvent.click(screen.getByLabelText("Pause event display"));
    const newer = { ...state, events: [{ ...state.events[0], id: "newer-event", ordinal: 100000, message: "New real snapshot marker" }, ...state.events] };
    rerender(<EventTerminal state={newer} inspect={inspect} />);
    expect(screen.queryByText("New real snapshot marker")).toBeNull();
    fireEvent.click(screen.getByLabelText("Resume event display")); expect(screen.getByText("New real snapshot marker")).toBeTruthy();
    fireEvent.change(screen.getByLabelText("Search event terminal"), { target: { value: "New real snapshot marker" } });
    fireEvent.click(screen.getByText("New real snapshot marker")); fireEvent.click(screen.getByText(/Inspect persisted evidence/));
    expect(inspect).toHaveBeenCalledWith("newer-event");
    fireEvent.change(screen.getByLabelText("Event provenance"), { target: { value: "runtime" } }); expect(screen.queryByText("New real snapshot marker")).toBeNull();
  });
  it("links persisted evidence to its actual investigation and escapes untrusted text", () => {
    const navigate = vi.fn(), event = state.events.find(e => e.incidentId)!;
    const altered = { ...state, events: [{ ...event, message: "<script>never execute stored content</script>" }, ...state.events.filter(e => e.id !== event.id)] };
    const { container } = render(<EvidenceInspector state={altered} focusId={event.id} navigate={navigate} />);
    expect(container.querySelector("script")).toBeNull(); expect(screen.getByText("<script>never execute stored content</script>")).toBeTruthy();
    fireEvent.click(screen.getByText("Open linked investigation")); expect(navigate).toHaveBeenCalledWith("Investigations", event.incidentId);
  });
  it("selects real graph nodes using React Flow and its accessible entity list", async () => {
    const select = vi.fn(), dispatch = vi.fn();
    const { container } = render(<div style={{ width: 1280, height: 760 }}><AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={dispatch} select={select} /></div>);
    await waitFor(() => expect(container.querySelector(".react-flow__node")).toBeTruthy());
    const firstNode = container.querySelector(".react-flow__node")!; fireEvent.click(firstNode); expect(select).toHaveBeenCalled();
    fireEvent.click(within(container.querySelector<HTMLElement>(".network-directory")!).getByText(state.agents[0].name)); expect(select).toHaveBeenLastCalledWith({ kind: "agent", id: state.agents[0].id });
    fireEvent.click(screen.getByLabelText("Reset network positions")); expect(dispatch).toHaveBeenCalledWith({ type: "reset-nodes" });
  });
  it("persists actual React Flow keyboard node movement and restores the position", async () => {
    const { container } = render(<GraphHarness />);
    await waitFor(() => expect(container.querySelector(".react-flow__node")).toBeTruthy());
    const node = container.querySelector(".react-flow__node")!;
    fireEvent.click(node); fireEvent.keyDown(node, { key: "ArrowRight" });
    await waitFor(() => expect(Object.keys(JSON.parse(screen.getByTestId("positions").textContent!)).length).toBeGreaterThan(0));
    expect(Object.keys(JSON.parse(screen.getByTestId("positions").textContent!))[0]).toMatch(/^n-[a-f0-9]{16}$/);
  });
  it("renders larger factual nodes, expands groups and focuses search results", async () => {
    const select = vi.fn();
    const { container } = render(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={() => {}} select={select} />);
    await waitFor(() => expect(container.querySelector(".node-facts")).toBeTruthy());
    expect(container.querySelector(".node-heading strong")).toBeTruthy();
    const initial = container.querySelectorAll(".network-directory button").length;
    fireEvent.click(screen.getByText(/^Expand \d+ records$/));
    expect(container.querySelectorAll(".network-directory button").length).toBeGreaterThan(initial);
    fireEvent.change(screen.getByLabelText("Find network entity"), { target: { value: state.agents[0].name } });
    fireEvent.keyDown(screen.getByLabelText("Find network entity"), { key: "Enter" });
    await waitFor(() => expect(container.querySelector(".security-node.selected")).toBeTruthy());
    fireEvent.change(screen.getByLabelText("Network provenance filter"), { target: { value: "Local runtime" } });
    expect(container.querySelectorAll(".network-directory button")).toHaveLength(0);
    fireEvent.click(screen.getByText("Clear filters")); expect(container.querySelectorAll(".network-directory button").length).toBeGreaterThan(0);
  });
  it("changes the actual React Flow viewport through zoom controls", async () => {
    const { container } = render(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={() => {}} select={() => {}} />);
    await waitFor(() => expect(container.querySelector(".react-flow__viewport")).toBeTruthy());
    const viewport = container.querySelector<HTMLElement>(".react-flow__viewport")!;
    const initial = viewport.style.transform;
    fireEvent.click(screen.getByLabelText("Zoom In"));
    await waitFor(() => expect(viewport.style.transform).not.toBe(initial));
    fireEvent.click(screen.getByLabelText("Fit network"));
    expect(screen.getByLabelText("Center selected node")).toBeTruthy();
  });
  it("commits a node mouse drag without opening an inspector from the following click", async () => {
    const dispatch = vi.fn(), select = vi.fn();
    const { container } = render(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={dispatch} select={select} />);
    await waitFor(() => expect(container.querySelector(".react-flow__node")).toBeTruthy());
    const node = container.querySelector(".react-flow__node")!;
    fireEvent.mouseDown(node, { view: window, button: 0, clientX: 100, clientY: 100 });
    fireEvent.mouseMove(window, { view: window, buttons: 1, clientX: 220, clientY: 180 });
    fireEvent.mouseUp(window, { view: window, button: 0, clientX: 220, clientY: 180 });
    await waitFor(() => expect(dispatch).toHaveBeenCalledWith(expect.objectContaining({ type: "position" })));
    fireEvent.click(node); expect(select).not.toHaveBeenCalled();
  });
  it("pans the React Flow viewport with a canvas mouse gesture", async () => {
    const { container } = render(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={() => {}} select={() => {}} />);
    await waitFor(() => expect(container.querySelector(".react-flow__pane")).toBeTruthy());
    const pane = container.querySelector(".react-flow__pane")!, viewport = container.querySelector<HTMLElement>(".react-flow__viewport")!;
    const initial = viewport.style.transform;
    fireEvent.mouseDown(pane, { view: window, button: 0, clientX: 80, clientY: 80 });
    fireEvent.mouseMove(window, { view: window, buttons: 1, clientX: 200, clientY: 160 });
    fireEvent.mouseUp(window, { view: window, button: 0, clientX: 200, clientY: 160 });
    await waitFor(() => expect(viewport.style.transform).not.toBe(initial));
  });
  it("highlights exact persisted request paths selected from the timeline", async () => {
    const event = state.events.find(e => e.module === "Gateway" && e.requestId)!;
    const { container, rerender } = render(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={() => {}} select={() => {}} eventId={event.id} />);
    await waitFor(() => expect(container.querySelector(".evidence-linked")).toBeTruthy());
    rerender(<AgentGraph state={state} layout={defaultLayout({ width: 1280, height: 760 })} dispatch={() => {}} select={() => {}} eventId="nonexistent-event" />);
    expect(container.querySelector(".evidence-linked")).toBeNull();
  });
  it("keeps scroll position when a user inspects old events and offers expanded rows", () => {
    const { rerender } = render(<EventTerminal state={state} inspect={() => {}} />);
    fireEvent.click(screen.getByText("Expand rows")); expect(document.querySelector(".investigation-mode")).toBeTruthy();
    fireEvent.click(screen.getAllByRole("button").find(b => b.className === "log-line")!);
    const log = screen.getByLabelText("Persisted security event log");
    Object.defineProperty(log, "scrollHeight", { configurable: true, value: 900 }); log.scrollTop = 123;
    rerender(<EventTerminal state={{ ...state, events: [{ ...state.events[0], id: "more-records", ordinal: 10000 }, ...state.events] }} inspect={() => {}} />);
    expect(log.scrollTop).toBe(123);
    fireEvent.scroll(log); expect((screen.getByLabelText("Follow") as HTMLInputElement).checked).toBe(false);
  });
  it("switches side-by-side/unified forensic diffs while escaping malicious-looking content", () => {
    const { container } = render(<MemoryDiff before="Trusted policy." after="<img src=x onerror=alert(1)>" parentVersion={1} version={2} />);
    expect(container.querySelector("img")).toBeNull(); expect(screen.getByText("<img src=x onerror=alert(1)>")).toBeTruthy();
    fireEvent.click(screen.getByText("Unified diff")); expect(container.querySelector(".memory-diff.unified")).toBeTruthy();
    expect(screen.getByText(/Text changes are not an attack verdict/)).toBeTruthy();
  });
});
