"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {sponsorSnapshot,sponsorPreflight} from "@/server/sponsors";
import {sponsorActionSchema,type SponsorAction} from "@/lib/sponsor-contract";
import type {Wire} from "@/lib/view-types";
type Snapshot=Wire<Awaited<ReturnType<typeof sponsorSnapshot>>>;
type Preview=Awaited<ReturnType<typeof sponsorPreflight>>;
export default function SponsorIntegrations({csrf,navigate}:{csrf:string;navigate:(name:string,id?:string)=>void}) {
  const [data,setData]=useState<Snapshot>(),[action,setAction]=useState<SponsorAction["action"]>("scan"),[target,setTarget]=useState<SponsorAction["target"]>("vulnerable"),[query,setQuery]=useState("synthetic research"),[incident,setIncident]=useState(""),[reference,setReference]=useState(""),[fixture,setFixture]=useState(true),[scenario,setScenario]=useState<SponsorAction["scenario"]>("normal");
  const [pending,setPending]=useState<SponsorAction>(),[preview,setPreview]=useState<Preview>(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<unknown>(),[muted,setMuted]=useState(true),[audioUrl,setAudioUrl]=useState("");
  const audio=useRef<HTMLAudioElement>(null);
  const refresh=useCallback(async()=>{const r=await fetch("/api/sponsors",{cache:"no-store",signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error("Integration status unavailable; verify local administration and migrations");setData(await r.json());},[]);
  useEffect(()=>{const start=setTimeout(()=>{void refresh().catch(e=>setError(e.message));},0);const timer=setInterval(()=>{void refresh().catch(()=>{});},5000);return()=>{clearTimeout(start);clearInterval(timer);};},[refresh]);
  useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl);},[audioUrl]);
  const post=async(path:string,body:unknown)=>{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json","x-ghostops-csrf":csrf},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error??"Local action rejected");return v;};
  const inspect=async()=>{setBusy(true);setError("");setPreview(undefined);try{const input=sponsorActionSchema.parse({commandId:crypto.randomUUID(),action,...(action==="scan"?{target,...(target==="runtime-artifact"?{requestId:reference}: {})}:{}),...(["context","search"].includes(action)?{query}:{}),...(action==="context"?{fixture}:{}),...(action==="narrate"?{incidentId:incident}:{}),...(action==="model-org"?{scenario,...(reference?{contextId:reference}: {})}: {})});const p=await post("/api/sponsors/preflight",input);setPending({...input,approvalToken:p.approvalToken});setPreview(p);}catch(e){setError(e instanceof Error?e.message:"Preflight failed");}finally{setBusy(false);}};
  const execute=async()=>{if(!pending)return;setBusy(true);setError("");try{const r=await post("/api/sponsors",pending);setResult({runId:r.runId,status:r.status,result:r.result,replayed:r.replayed});if(r.audio){const bytes=Uint8Array.from(atob(r.audio),c=>c.charCodeAt(0));setAudioUrl(URL.createObjectURL(new Blob([bytes],{type:"audio/mpeg"})));}await refresh();}catch(e){setError(e instanceof Error?e.message:"Dispatch uncertain; inspect receipt before retry");}finally{setBusy(false);}};
  return <section className="lab-panel"><h2>Sponsor capabilities / evidence first</h2><p>Optional transfers require configuration and exact-action approval. SQLite and the guarded MCP gateway remain authoritative. Fixtures are not live services.</p><p role="status">{error||"No provider call or cloud deployment occurs merely by opening this panel."}</p>
    <div className="lab-actions" onChange={()=>{setPending(undefined);setPreview(undefined);}}><label>Action<select value={action} onChange={e=>{setAction(e.target.value as SponsorAction["action"]);setPending(undefined);setPreview(undefined);}}>{Object.keys({scan:0,context:0,"model-org":0,telemetry:0,analytics:0,index:0,search:0,narrate:0,otlp:0}).map(v=><option key={v}>{v}</option>)}</select></label>
      {action==="scan"&&<label>Approved target<select value={target} onChange={e=>setTarget(e.target.value as SponsorAction["target"])}>{["vulnerable","corrected","approved-repository","runtime-artifact"].map(t=><option key={t}>{t}</option>)}</select></label>}
      {["context","search"].includes(action)&&<label>Bounded synthetic query<input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label>}
      {action==="context"&&<label><input type="checkbox" checked={fixture} onChange={e=>setFixture(e.target.checked)}/> Local provenance fixture — NOT Senso API</label>}
      {action==="model-org"&&<label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value as SponsorAction["scenario"])}>{["normal","prompt-injection","memory-poisoning"].map(s=><option key={s}>{s}</option>)}</select></label>}
      {(action==="model-org"||target==="runtime-artifact"&&action==="scan")&&<label>{action==="model-org"?"Optional approved context ID":"Verified artifact request ID"}<input value={reference} maxLength={36} onChange={e=>setReference(e.target.value)}/></label>}
      {action==="narrate"&&<label>Persisted incident ID<input value={incident} maxLength={36} onChange={e=>setIncident(e.target.value)}/></label>}
      <button className="button" disabled={busy} onClick={()=>void inspect()}>Inspect exact action</button></div>
    {preview&&<div className="evidence-json"><h3>Fresh approval / {preview.sponsor}</h3><p>{preview.destination} · {preview.mode} · {preview.recordCount} projected records</p><p>{preview.cost}</p><p>{preview.configurationDetail}</p>{preview.modelPlan&&<pre>{JSON.stringify(preview.modelPlan,null,2)}</pre>}<p>Payload digest {preview.payloadHash}. Approval expires in two minutes. Changing controls requires a new preflight; execution uses only the inspected configuration.</p><button className="button" disabled={busy||!preview.canExecute} onClick={()=>void execute()}>{busy?"Executing approved action…":"Confirm inspected action / may incur configured service costs"}</button></div>}
    {audioUrl&&<div><label><input type="checkbox" checked={muted} onChange={e=>setMuted(e.target.checked)}/>Mute narration</label><audio ref={audio} src={audioUrl} muted={muted} controls/><button className="button" onClick={()=>{audio.current?.pause();if(audio.current)audio.current.currentTime=0;}}>Stop</button></div>}
    {result!==undefined&&<details open><summary>Actual action receipt</summary><pre className="evidence-json">{JSON.stringify(result,null,2)}</pre></details>}
    <h3>Capability registry</h3>{data?.integrations.map(i=><article className="evidence-card" key={i.sponsor}><h3>{i.sponsor} · {i.status}</h3><p>{i.capability}</p><p>{i.limitation} · {i.destination}</p><small>{i.lastVerification?`Receipt ${i.receiptId} / ${i.lastVerification}`:"No successful service receipt"}</small></article>)}
    <h3>Persisted scan comparisons</h3>{data?.scans.map(s=><details key={s.id}><summary>{s.target} / Semgrep {s.scannerVersion} / {s.id.slice(0,8)}</summary><pre className="evidence-json">{JSON.stringify({files:s.files,findings:s.findings,comparison:s.comparison,requestId:s.requestId},null,2)}</pre></details>)}
    <h3>Recent integration receipts</h3>{data?.runs.map(r=><details key={r.id}><summary>{r.sponsor} / {r.action} / {r.mode} / {r.status}</summary><pre className="evidence-json">{JSON.stringify(r.result,null,2)}</pre>{r.status==="running"&&r.action==="model-org"&&<button className="button" onClick={()=>void post("/api/sponsors/cancel",{runId:r.id}).then(refresh).catch(e=>setError(e.message))}>Cancel at safe boundaries</button>}</details>)}
    <button className="button" onClick={()=>navigate("Investigations")}>Open authoritative investigations</button>
  </section>;
}
