"use client";
import { memo, useCallback, useEffect, useMemo, useRef, useState, type Dispatch } from "react";
import { Background, Controls, Handle, Position, ReactFlow, type Node, type NodeProps, type NodeChange } from "@xyflow/react";
import type { huntSnapshot } from "@/server/hunt";
import type { Wire, State } from "@/lib/view-types";
import type { Preferences, WorkspaceAction } from "@/lib/workspace-model";
import { huntGraph } from "@/lib/hunt-graph";
import { downloadEvidence } from "./lab-benchmarks";
type Data = Wire<Awaited<ReturnType<typeof huntSnapshot>>>;
type HuntNode = Node<{ label: string; kind: string; state: string; selectedEvidence: boolean }, "hunt">;
const HuntNodeView = memo(function HuntNodeView({ data, selected }: NodeProps<HuntNode>) {
  return <div className={`security-node ${selected || data.selectedEvidence ? "selected" : ""}`}><Handle type="target" position={Position.Left} isConnectable={false} /><div className="node-heading"><div><span className="node-kind">{data.kind.toUpperCase()}</span><strong title={data.label}>{data.label}</strong></div></div><p className="node-subtitle">Evidence-linked local runtime entity</p><dl className="node-facts"><div><dt>Current state</dt><dd>{data.state}</dd></div><div><dt>Attribution</dt><dd>Verified record / not intent</dd></div></dl><footer>Actual persisted relationship</footer><Handle type="source" position={Position.Right} isConnectable={false} /></div>;
});
const nodeTypes = { hunt: HuntNodeView };
export default function ThreatHunt({ state, csrf, layout, dispatch, navigate }: { state: State; csrf: string; layout: Preferences; dispatch: Dispatch<WorkspaceAction>; navigate: (name: string, id?: string) => void }) {
  const [data, setData] = useState<Data>(), [error, setError] = useState(""), [selected, select] = useState(""), [focus, setFocus] = useState(""), [category, setCategory] = useState("all"), [eventId, setEvent] = useState(""), [paused, pause] = useState(false);
  const [members, setMembers] = useState<string[]>([]), [busy, setBusy] = useState(false), [authorizeAuto, allowAuto] = useState(false);
  const [pending, setPending] = useState<Record<string, unknown>>();
  const [draft, setDraft] = useState<Record<string, { x: number; y: number }>>({});
  const [positions, setPositions] = useState<Record<string, { x: number; y: number }>>({});
  const lock = useRef(false), drag = useRef(0), version = useRef(0);
  const place = useCallback((nodes: ReturnType<typeof huntGraph>["nodes"]) => { setPositions(previous => { const positions = { ...previous }; for (const n of nodes) { if (positions[n.id]) continue; const x = ({ agent: 0, session: 1, tool: 2, source: 2, resource: 3, memory: 4, trap: 4, finding: 4, response: 5 }[n.kind] ?? 2) * 380; const y = Math.max(-260, ...Object.values(positions).filter(p => p.x === x).map(p => p.y)) + 260; positions[n.id] = { x, y }; } return positions; }); }, []);
  const refresh = useCallback(async () => { const current = ++version.current; const r = await fetch("/api/hunt", { cache: "no-store", signal: AbortSignal.timeout(8000) }); if (!r.ok) throw new Error("Threat Hunt unavailable; use a migrated isolated Phase 10 instance."); const next: Data = await r.json(); if (current === version.current) { setData(next); for (const investigation of next.cases) place(huntGraph(next.links, investigation.id).nodes); } }, [place]);
  const invalidate = useCallback(() => { version.current++; }, []);
  useEffect(() => { if (paused) return; let active = true; let timer: ReturnType<typeof setTimeout>; const poll = async () => { try { await refresh(); } catch (e) { if (active) setError((e as Error).message); } if (active) timer = setTimeout(() => void poll(), 2000); }; void poll(); return () => { active = false; invalidate(); clearTimeout(timer); }; }, [paused, refresh, invalidate]);
  const mutate = async (input: Record<string, unknown>, retry = false) => {
    if (lock.current || pending && !retry) return; lock.current = true; setBusy(true); setError("");
    const payload = retry ? input : { commandId: crypto.randomUUID(), ...input }; setPending(payload);
    try { const r = await fetch("/api/hunt", { method: "POST", headers: { "content-type": "application/json", "x-ghostops-csrf": csrf }, body: JSON.stringify(payload), signal: AbortSignal.timeout(15000) }); const receipt = await r.json(); setPending(undefined); if (!r.ok) throw new Error(receipt.error ?? "Command rejected"); await refresh(); }
    catch (e) { setError((e as Error).message); } finally { lock.current = false; setBusy(false); }
  };
  const investigation = data?.cases.find(c => c.id === selected) ?? data?.cases[0];
  const scope = data?.scopes.find(s => s.id === investigation?.scopeId);
  const plans = useMemo(() => data?.plans.filter(p => p.caseId === investigation?.id) ?? [], [data?.plans, investigation?.id]);
  const projection = useMemo(() => huntGraph(data?.links ?? [], investigation?.id ?? "", focus, category), [data?.links, investigation?.id, focus, category]);
  const nodes = useMemo<HuntNode[]>(() => projection.nodes.map(n => {
    return { id: n.id, type: "hunt", width: 304, height: 218, position: draft[n.id] ?? layout.positions[n.id] ?? positions[n.id] ?? { x: 0, y: 0 }, data: { label: n.kind === "agent" ? state.agents.find(a => a.id === n.label)?.name ?? n.label : n.label, kind: n.kind === "agent" ? "authenticated agent" : n.kind, state: n.kind === "agent" ? state.agents.find(a => a.id === n.label)?.status ?? "recorded" : n.kind === "response" ? plans.find(p => p.id === n.label)?.status ?? "recorded" : "observed", selectedEvidence: projection.edges.some(e => e.eventId === eventId && [e.source, e.target].includes(n.id)) } };
  }), [projection, draft, layout.positions, positions, state.agents, plans, eventId]);
  const onNodesChange = useCallback((changes: NodeChange<HuntNode>[]) => { for (const c of changes) if (c.type === "position" && c.position) setDraft(d => ({ ...d, [c.id]: c.position! })); }, []);
  const edges = useMemo(() => projection.edges.map(l => ({ id: l.id, source: l.source, target: l.target, label: l.relation, style: { stroke: l.category === "confirmed-violation" ? "#d68178" : l.category === "suspected-manipulation" ? "#c2a16f" : "#718f99", strokeWidth: l.eventId === eventId ? 4 : 2, strokeDasharray: l.category === "inferred-relationship" ? "6 5" : undefined }, labelStyle: { fill: "#d4dce0", fontSize: 13 }, labelBgStyle: { fill: "#151c21" } })), [projection.edges, eventId]);
  const events = data?.events.filter(e => data.links.some(l => l.caseId === investigation?.id && l.eventId === e.id)) ?? [];
  const event = events.find(e => e.id === eventId);
  const blocked = busy || !!pending;
  const participants = (scope?.agentIds ?? []) as string[];
  const configure = (mode: string) => mutate({ action: "configure", scopeId: scope!.id, mode, learningWindow: scope!.learningWindow, evaluationWindow: scope!.evaluationWindow, maxActionsPerHour: scope!.maxActionsPerHour });
  return <section className="security-lab"><header><span className="eyebrow">LOCAL COUNTERINTELLIGENCE / EVIDENCE FIRST</span><h2>Ghost Hunt</h2><p>Observed facts, confirmed policy violations and suspected manipulation remain separate. Scope membership is operator grouping, not a causal link. No model inference implied.</p></header>
    <div className="lab-actions"><label>Investigation<select aria-label="Hunt investigation" value={investigation?.id ?? ""} onChange={e => { select(e.target.value); setFocus(""); setEvent(""); allowAuto(false); }}>{data?.cases.map(c => <option key={c.id} value={c.id}>{c.id.slice(0, 8)} · {c.status}</option>)}</select></label><button className="button" onClick={() => pause(v => !v)}>{paused ? "Resume" : "Pause"} display updates</button><button className="button" disabled={!investigation} onClick={() => { if (investigation) void downloadEvidence("hunt", investigation.id).catch(e => setError(e.message)); }}>Export hunt evidence ZIP</button></div>
    <p role="status">{error || investigation?.summary || "Create an explicit synthetic scope or run npm run hunt:demo on an isolated instance."}</p>
    {pending && <div role="alert">Uncertain delivery / command {String(pending.commandId)}. Inspect history first.<button className="button" disabled={busy} onClick={() => void mutate(pending, true)}>Retry exact command</button><button className="button" disabled={busy} onClick={() => setPending(undefined)}>History inspected; clear pending receipt</button></div>}
    <details><summary>Configure a synthetic organization</summary><p>Registration grants no new permissions. These identities must already have explicitly provisioned capabilities.</p>{state.agents.filter(a => !a.simulated && a.status === "active").map(a => <label key={a.id}><input type="checkbox" checked={members.includes(a.id)} onChange={e => setMembers(ids => e.target.checked ? [...ids, a.id].slice(0, 8) : ids.filter(id => id !== a.id))} />{a.name}</label>)}<button className="button" disabled={blocked || !members.length} onClick={() => void mutate({ action: "scope", name: "Operator-scoped synthetic organization", agentIds: members })}>Create OBSERVE scope</button></details>
    {scope && <details><summary>Behavior baselines and response policy · {scope.mode} / revision {scope.revision}</summary><p>Baseline window {scope.learningWindow}; evaluation window {scope.evaluationWindow}. Frozen only from authenticated permitted untainted sessions. No silent retraining. {scope.maxActionsPerHour} response actions/hour maximum.</p>{participants.map(id => <button key={id} className="button" disabled={blocked} onClick={() => void mutate({ action: "baseline", scopeId: scope.id, actorId: id })}>Freeze baseline · {id}</button>)}<div className="lab-actions"><button className="button" disabled={blocked} onClick={() => void configure("OBSERVE")}>OBSERVE only</button><button className="button" disabled={blocked} onClick={() => void configure("APPROVAL_REQUIRED")}>Require operator approval</button><label><input type="checkbox" checked={authorizeAuto} onChange={e => allowAuto(e.target.checked)} />I explicitly authorize bounded automatic quarantine for this synthetic scope</label><button className="button" disabled={blocked || !authorizeAuto} onClick={() => void configure("AUTOMATIC")}>Enable scoped AUTOMATIC</button></div><p>Legacy deterministic correlation is independent and remains enforced. New plans cannot bypass it.</p></details>}
    <div className="lab-actions"><label>Neighborhood / entity<select aria-label="Hunt neighborhood" value={focus} onChange={e => { setFocus(e.target.value); place(huntGraph(data?.links ?? [], investigation?.id ?? "", e.target.value, category).nodes); }}><option value="">Relevant investigation entities</option>{[...new Set(data?.links.filter(l => l.caseId === investigation?.id).flatMap(l => [l.source, l.target]))].map(id => <option key={id} value={id}>{id}</option>)}</select></label><label>Evidence category<select aria-label="Hunt evidence category" value={category} onChange={e => { setCategory(e.target.value); place(huntGraph(data?.links ?? [], investigation?.id ?? "", focus, e.target.value).nodes); }}>{["all", "observed", "confirmed-violation", "suspected-manipulation", "inferred-relationship"].map(c => <option key={c}>{c}</option>)}</select></label></div>
    <div style={{ height: 480, minHeight: 320 }}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView minZoom={.65} maxZoom={1.8} fitViewOptions={{ minZoom: .65, maxZoom: 1, padding: .15 }} nodesConnectable={false} onNodesChange={onNodesChange} onNodeDragStart={() => { drag.current = Date.now() + 500; }} onNodeDragStop={(_, n) => { drag.current = Date.now() + 250; dispatch({ type: "position", id: n.id, position: n.position }); setDraft(d => { const next = { ...d }; delete next[n.id]; return next; }); }} onNodeClick={(_, n) => { if (Date.now() < drag.current) return; const record = projection.nodes.find(p => p.id === n.id); if (record?.kind === "agent") navigate("Agent inspector", record.label); if (record?.kind === "memory") navigate("MemoryGuard", record.label); }} onEdgeClick={(_, edge) => { const l = projection.edges.find(l => l.id === edge.id); if (l) setEvent(l.eventId); }}><Background color="#253038" gap={24} /><Controls showInteractive={false} /></ReactFlow></div>
    <p>{projection.truncated ? "Bounded view: choose a neighborhood/category to explore more." : "Every connection links to persisted evidence. Pan, zoom, drag nodes or select a timeline event."}</p>
    <div className="lab-actions">{participants.map(id => <button key={id} className="button" disabled={blocked} onClick={() => void mutate({ action: "preview", scopeId: scope!.id, actorId: id })}>Preview response · {id}</button>)}</div>
    {plans.map(plan => <details key={plan.id}><summary>{plan.action} / {plan.actorId} / {plan.status} / {plan.mode}</summary><pre>{JSON.stringify({ session: plan.sessionId, expiresAt: plan.expiresAt, evidenceIds: plan.evidenceIds, receipt: plan.result }, null, 2)}</pre><button className="button" disabled={blocked || plan.status !== "pending" || plan.mode !== "APPROVAL_REQUIRED"} onClick={() => void mutate({ action: "approve", planId: plan.id })}>Approve revalidated plan</button><button className="button" disabled={blocked || plan.status !== "pending"} onClick={() => void mutate({ action: "reject", planId: plan.id })}>Reject plan</button><button className="button" onClick={() => navigate("Runtime sessions", plan.actorId)}>Existing restoration / memory controls</button></details>)}
    <h3>Chronological evidence</h3>{events.map(e => <details key={e.id} open={e.id === eventId}><summary onClick={() => setEvent(e.id)}>{e.ordinal} / {new Date(e.createdAt).toLocaleTimeString()} / {e.actorId} / {e.module} / {e.kind}</summary><p>{e.message}</p><code>{e.id} · request {e.requestId}</code><pre>{JSON.stringify(e.details, null, 2)}</pre>{e.incidentId && <button className="button" onClick={() => navigate("Investigations", e.incidentId!)}>Open linked investigation</button>}<button className="button" onClick={() => navigate("Agent inspector", e.actorId)}>Inspect authenticated agent</button>{scope && e.requestId && <button className="button" disabled={blocked} onClick={() => void mutate({ action: "deploy", scopeId: scope.id, template: "adaptive", reasonEventId: e.id })}>Select approved adaptive decoy overlay</button>}</details>)}
    {event && <p>Graph highlighting uses selected event {event.id}; source context is not proof of influence.</p>}
    <h3>Synthetic deception overlays</h3>{data?.deployments.filter(d => d.scopeId === scope?.id).map(d => <p key={d.id}>{d.template} · {d.active ? "active" : "retired"} · {d.selectionReason}<button className="button" disabled={blocked || !d.active} onClick={() => void mutate({ action: "cleanup", deploymentId: d.id })}>Retire scoped overlay</button></p>)}
    <p>{data?.limitations} Cursor ordinal {data?.cursor?.ordinal ?? "not initialized"}. Showing {data?.coverage.displayedLinks ?? 0} / {data?.coverage.totalLinks ?? 0} relationships{data?.coverage.truncated ? "; older links outside this bounded dashboard sample remain persisted" : ""}. History panels are bounded; ZIP export refuses oversize packages instead of silently truncating. Layout/node coordinates confer no authority.</p>
  </section>;
}
