"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {sentinelStartSchema,type SentinelStart} from "@/lib/sentinel-contract";
type Run={id:string;status:string;createdAt:string;configuration:SentinelStart;assessment:{status:string;verifiedSponsors:string[];checks:{requirement:string;status:string;detail:string}[]};observations:{id:string;kind:string;createdAt:string;data:unknown}[];requests:{id:string;actorId:string;resource:string;allowed:boolean;reason:string;execution?:{handlerExecuted?:boolean;completed?:boolean;dispatch?:string}|null;incidentId:string|null}[];publication:{title:string;body:string;status:string;result:unknown}|null;memoryIntegrity:{ownerId:string;verified:boolean}[]};
type Snapshot={model:{provider:string;model:string|null;ready:boolean};webEnabled:boolean;github:{target:string;enabled:boolean;configured:boolean};runs:Run[];backends:{sponsor:string;enabled:boolean;configured:boolean}[];monitors:{runId:string;status:string;nextCheck:string;remaining:number}[]};
type Plan={approvalToken:string;canExecute:boolean;configuration?:SentinelStart;title?:string;body?:string;digest?:string;target?:string;[key:string]:unknown};
export default function WebSentinel({csrf,navigate}:{csrf:string;navigate:(name:string,id?:string)=>void}){
  const [data,setData]=useState<Snapshot>();const [selected,setSelected]=useState("");const [mode,setMode]=useState<SentinelStart["mode"]>("offline");const [target,setTarget]=useState<SentinelStart["target"]>("vulnerable");const [objective,setObjective]=useState("Investigate approved public advisories for this repository, run useful local checks, and prepare a truthful research report.");
  const [sources,setSources]=useState<SentinelStart["sources"]>(["osv"]);const [backends,setBackends]=useState<SentinelStart["backends"]>([]);const [injection,setInjection]=useState(false);const [plan,setPlan]=useState<Plan>();const [publishing,setPublishing]=useState(false);const [confirmation,setConfirmation]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const revision=useRef(0);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const r=await fetch("/api/sentinel",{cache:"no-store",signal:AbortSignal.any([AbortSignal.timeout(5000),...(signal?[signal]:[])])});if(!r.ok)throw new Error("Local authenticated Sentinel status unavailable");const value=await r.json();if(!signal?.aborted)setData(value);},[]);
  useEffect(()=>{const controller=new AbortController();let loading=false;const load=()=>{if(loading||controller.signal.aborted)return;loading=true;void refresh(controller.signal).catch(()=>{if(!controller.signal.aborted)setError("Status unavailable; no successful operation inferred.");}).finally(()=>{loading=false;});};load();const timer=setInterval(load,5000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
  const invalidate=()=>{revision.current++;setPlan(undefined);setConfirmation("");};
  async function post(path:string,payload:unknown){const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json","x-ghostops-csrf":csrf},body:JSON.stringify(payload),signal:AbortSignal.timeout(40000)});if(!r.ok)throw new Error("Operation rejected, unavailable or stale. No success inferred; inspect current records before retry.");return r.json();}
  async function perform(job:()=>Promise<void>){setBusy(true);setError("");try{await job();await refresh();}catch(e){setError(e instanceof Error?e.message:"Operation failed safely");}finally{setBusy(false);}}
  async function inspect(path:string,payload:unknown,publication:boolean){const current=revision.current;setPublishing(publication);const preview=await post(path,payload);if(current===revision.current)setPlan(preview);}
  const run=data?.runs.find(r=>r.id===selected)??data?.runs[0];
  const command=(action:string)=>({commandId:crypto.randomUUID(),runId:run?.id,action});
  return <div className="lab-panel"><div className="panel-heading"><div><span className="eyebrow">BOUNDED SECURITY INTELLIGENCE</span><h2>Web Sentinel</h2></div><span>{data?.model.provider??"unconfigured"} / {data?.model.model??"no model"}</span></div>
    <p>Offline decisions are scripted. Live web is not autonomous inference. Publication and three-sponsor completion require actual verified receipts.</p>
    {error&&<p role="alert" className="red-text">{error}</p>}
    <div className="lab-controls"><label>Objective<textarea aria-label="Sentinel objective" value={objective} maxLength={1000} onChange={e=>{setObjective(e.target.value);invalidate();}}/></label>
      <label>Execution mode<select value={mode} onChange={e=>{setMode(e.target.value as typeof mode);invalidate();}}><option value="offline">Offline scripted / actual local tools</option><option value="live-web" disabled={!data?.webEnabled}>Live public web / scripted decisions</option><option value="model" disabled={!data?.model.ready||!data.webEnabled}>Actual model-driven / approval required</option></select></label>
      <label>Approved repository<select value={target} onChange={e=>{setTarget(e.target.value as typeof target);invalidate();}}><option value="vulnerable">Synthetic vulnerable snapshot</option><option value="corrected">Synthetic corrected snapshot</option><option value="approved-repository">Operator-configured repository</option></select></label>
      <fieldset><legend>Approved sources</legend>{(["osv","cisa","github"] as const).map(source=><label key={source}><input type="checkbox" checked={sources.includes(source)} onChange={e=>{setSources(s=>e.target.checked?[...s,source]:s.filter(v=>v!==source));invalidate();}}/>{source.toUpperCase()}</label>)}</fieldset>
      <fieldset><legend>Explicit minimized backend transfer</legend>{data?.backends.map(b=><label key={b.sponsor}><input type="checkbox" disabled={!b.enabled||!b.configured} checked={backends.includes(b.sponsor as typeof backends[number])} onChange={e=>{setBackends(v=>e.target.checked?[...v,b.sponsor as typeof backends[number]]:v.filter(x=>x!==b.sponsor));invalidate();}}/>{b.sponsor} — {b.enabled&&b.configured?"configured, not verified":"configuration required"}</label>)}</fieldset>
      <label><input type="checkbox" checked={injection} onChange={e=>{setInjection(e.target.checked);invalidate();}}/>Separate synthetic injection fixture (not a genuine advisory)</label>
      <button className="button" disabled={busy||!csrf||!sources.length} onClick={()=>void perform(async()=>{await inspect("/api/sentinel/preflight",sentinelStartSchema.parse({commandId:crypto.randomUUID(),objective,mode,target,sources,backends,injection}),false);})}>Inspect exact run</button>
    </div>
    {plan&&<section aria-label="Exact Sentinel approval"><h3>{publishing?"Externally visible publication preview":"Run preflight — no inference dispatched"}</h3>{publishing?<><p>Target: {plan.target}</p><h4>{plan.title}</h4><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{plan.body}</pre><label>Type APPROVE PUBLICATION<input aria-label="Publication confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>:<pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify({...plan,approvalToken:"[approval held only in this session]"},null,2)}</pre>}
      <button className="button primary" disabled={busy||!plan.canExecute||publishing&&confirmation!=="APPROVE PUBLICATION"} onClick={()=>void perform(async()=>{if(publishing){await post("/api/sentinel",{...command("publish"),approvalToken:plan.approvalToken,confirmation});}else{const r=await post("/api/sentinel",{...plan.configuration,approvalToken:plan.approvalToken});setSelected(r.runId);}invalidate();})}>{publishing?"Approve this exact GitHub report":"Approve and start this bounded run"}</button><button className="button" onClick={invalidate}>Reject / close preview</button></section>}
    <label>Persisted run<select aria-label="Sentinel run" value={run?.id??""} onChange={e=>{setSelected(e.target.value);invalidate();}}><option value="" disabled>Select run</option>{data?.runs.map(r=><option value={r.id} key={r.id}>{r.id.slice(0,8)} / {r.status} / {r.configuration.mode}</option>)}</select></label>
    {run&&<><h3>{run.status} · challenge {run.assessment.status}</h3><p>Verified sponsors: {run.assessment.verifiedSponsors.join(", ")||"none"}. GitHub target: {data?.github.target}.</p><dl>{run.assessment.checks.map(c=><div key={c.requirement}><dt>{c.requirement} — {c.status}</dt><dd>{c.detail}</dd></div>)}</dl>
      <div className="panel-actions"><button className="button" disabled={busy||run.status!=="running"} onClick={()=>void perform(async()=>{await post("/api/sentinel",command("cancel"));invalidate();})}>Stop run</button><button className="button" disabled={busy||!["completed","partial"].includes(run.status)} onClick={()=>void perform(async()=>{await inspect("/api/sentinel",command("publication-preview"),true);})}>Inspect publication preview</button><button className="button" disabled={busy||run.configuration.mode==="offline"} onClick={()=>void perform(async()=>{await post("/api/sentinel",{...command("monitor"),intervalMinutes:60,maxChecks:2});})}>Monitor twice, hourly (no inference/publication)</button><button className="button" disabled={busy} onClick={()=>void perform(async()=>{await post("/api/sentinel",command("pause-monitor"));})}>Pause monitor</button><button className="button" disabled={busy} onClick={()=>void perform(async()=>{await post("/api/sentinel",command("resume-monitor"));})}>Resume monitor</button><a className="button" href={`/api/evidence/sentinel/${run.id}`}>Export authenticated evidence</a></div>
      {data?.monitors.filter(m=>m.runId===run.id).map(m=><p key={m.runId}>Monitor {m.status}; {m.remaining} checks remaining; next {m.nextCheck}</p>)}
      <h3>Actual tool decisions</h3>{run.requests.map(r=><div className="timeline-event" key={r.id}><strong>{r.reason==="TOOL_HANDLER_FAILED"?"AUTHORIZED · EXECUTION FAILED":r.allowed?(r.execution?.completed?"EXECUTED":"AUTHORIZED · NO COMPLETION RECEIPT"):"DENIED"} · {r.resource}</strong><p>{r.actorId} · {r.reason} · {r.id}</p>{r.incidentId&&<button className="button" onClick={()=>navigate("Investigations",r.incidentId!)}>Open investigation</button>}</div>)}
      <h3>Persisted execution timeline</h3>{run.observations.map(o=><details key={o.id}><summary>{o.createdAt} · {o.kind}</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(o.data,null,2)}</pre></details>)}
      {run.publication&&<details><summary>Report / publication: {run.publication.status}</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{run.publication.body}</pre><pre>{JSON.stringify(run.publication.result,null,2)}</pre></details>}
      <p>Protected policy verification: {run.memoryIntegrity.every(m=>m.verified)&&run.memoryIntegrity.length?"verified":"not established"}. No private reasoning is displayed.</p>
    </>}
  </div>;
}
