"use client";
import type { SectionProps } from "./console";
import { Badge, Empty, Panel, time } from "./ui";
export function DeveloperIntegrations({ state, navigate, control, busy }: Pick<SectionProps, "state" | "navigate"> & Partial<Pick<SectionProps, "control" | "busy">>) {
  const agents = state.agents.filter(a => a.integrationType === "external-node");
  return <Panel title="Developer integrations" eyebrow="EXTERNAL NODE · AUTHENTICATED MCP"><p>Only gateway-routed tools are protected. Registration and authorized sessions do not prove a process is online. Credentials are issued only to private local CLI files, never displayed here.</p>
    <details><summary>SDK and proxy quickstart</summary><pre className="evidence-json">{"npm run sdk:build\nnpm run external:manage -- --action provision --id live-external-research\nnpm run external:run -- --credential-file .ghostops/external/live-external-research-provision.json --action normal\nnpm run external:run -- --credential-file .ghostops/external/live-external-research-provision.json --action probe"}</pre><p>Independent projects use locally packed SDK/proxy packages. See docs/DEVELOPER_SDK.md and docs/MCP_PROXY.md. Use a new identity when already provisioned.</p></details>
    {!agents.length ? <Empty title="No provisioned external integrations" detail="Provision a restricted identity with the local operator CLI; an agent cannot enroll itself through SDK tools." /> : agents.map(agent => {
      const last = state.runtimeRequests.find(r => r.actorId === agent.id && r.identityVerified), sessions = state.sessions.filter(s => s.agentId === agent.id), cases = state.incidents.filter(i => i.actorId === agent.id && i.identityVerified);
      return <section className="inspector-section" key={agent.id}><div className="panel-heading"><h3>{agent.name}</h3><Badge value={agent.status} /></div><p><code>{agent.id}</code> · {agent.role} · {agent.integrationType}</p><p>{sessions.filter(s => s.active).length} authorized sessions in bounded snapshot · Last verified gateway activity: {last ? time(last.createdAt) : "none observed"}</p><pre className="evidence-json">{JSON.stringify(agent.permissions, null, 2)}</pre><div className="control-row"><button className="button small" onClick={() => navigate("Agent Registry", agent.id)}>Identity / behavior</button><button className="button small" onClick={() => navigate("Runtime sessions", agent.id)}>Gateway receipts</button>{control && <><button className="button danger small" disabled={busy || agent.status !== "active"} onClick={() => void control("quarantine", agent.id)}>Quarantine</button><button className="button small" disabled={busy || agent.status !== "active"} onClick={() => void control("revoke", agent.id)}>Revoke</button></>}</div>{cases.map(i => <button key={i.id} className="text-button" onClick={() => navigate("Investigations", i.id)}>INC-{i.id.slice(0, 8)} · {i.severity} / {i.status}</button>)}<p>Rotation/restoration: local CLI only; verifies signed memory and replaces credential/session. No old credential is revived.</p></section>;
    })}</Panel>;
}
