import { useState } from "react";
import { Activity, ArrowRight, CheckCheck, Clock, Code, FileText, Fingerprint, FlaskConical, Ghost, History, LockKeyhole, Play, Radar, RotateCcw, Shield, ShieldCheck, ShieldOff, Terminal, Unplug, Zap } from "lucide-react";
import type { Counts, Permissions } from "@/lib/schemas";
import type { State } from "@/lib/view-types";
import type { SectionProps } from "./console";
import { Badge, DetailRow, Empty, Panel, SectionLink, shortId, time } from "./ui";
import { ActivityTable, AgentNetwork } from "./overview";
export { Investigations } from "./investigations";
import { DemoStory } from "./demo-story";

function AgentSelector({ state, selected, onSelect }: { state: State; selected: string; onSelect: (id: string) => void }) { return <div className="tabs agent-tabs">{state.agents.map(a => <button className={selected === a.id ? "active" : ""} key={a.id} onClick={() => onSelect(a.id)}><span className={`identity-dot ${a.status === "active" ? "green" : "red"}`} />{a.name}<Badge value={a.status} /></button>)}</div>; }
function CountBars({ counts, title }: { counts: Counts; title: string }) {
  const values = Object.entries(counts);
  const max = Math.max(1, ...values.map(([, n]) => n));
  return <div className="count-bars"><span className="eyebrow">{title}</span>{values.length ? values.map(([label, count]) => <div key={label}><div className="bar-label"><code>{label}</code><span>{count}</span></div><div className="bar-track"><i style={{ width: `${count / max * 100}%` }} /></div></div>) : <p className="muted">No baseline observations yet.</p>}</div>;
}
export function AgentRegistry({ state, control, busy, focusId, navigate }: SectionProps) {
  const [selected, select] = useState(focusId ?? "research");
  const agent = state.agents.find(a => a.id === selected) ?? state.agents[0];
  if (!agent) return <Empty title="Registry not initialized" detail="Initialize the local environment in Demo Control." />;
  const permissions = agent.permissions as Permissions;
  const sessions = state.sessions.filter(s => s.agentId === agent.id);
  return <><AgentSelector state={state} selected={agent.id} onSelect={select} /><div className="two-column"><Panel title={agent.name} eyebrow="REGISTERED IDENTITY" action={<Badge value={agent.status} />}><div className="profile-summary"><div className="profile-avatar"><Fingerprint size={34} /></div><div><h3>{agent.role}</h3><p>{agent.trust === "authorized" ? "Known identity with explicit, scoped permissions." : "Registered identity; suspicious behavior requires investigation."}</p><span className="mono muted">agent://{agent.id}</span></div></div><DetailRow label="Trust state"><Badge value={agent.trust} /></DetailRow><DetailRow label="Behavioral baseline">{agent.profile?.observations ?? 0} authorized observations · {agent.profile?.frozen ? "frozen" : "learning"}</DetailRow><DetailRow label="Environment">Isolated simulation</DetailRow><DetailRow label="Authentication">Hashed credentials · bound sessions</DetailRow><div className="control-row"><button className="button danger" disabled={busy || agent.status === "quarantined"} onClick={() => void control("quarantine", agent.id)}><ShieldOff size={15} />Quarantine</button><button className="button" disabled={busy || agent.status === "revoked"} onClick={() => void control("revoke", agent.id)}><Unplug size={15} />Revoke</button><button className="button primary" disabled={busy || agent.status === "active"} onClick={() => void control("restore-agent", agent.id)}><RotateCcw size={15} />Restore agent</button></div></Panel>
    <Panel title="Permission boundaries" eyebrow="ENFORCED BEFORE EXECUTION"><div className="permission-block"><span className="eyebrow">PERMITTED TOOLS & OPERATIONS</span><div className="tag-list">{permissions.tools.map(t => <code key={t}>{t}</code>)}</div></div><div className="permission-block"><span className="eyebrow">PERMITTED RESOURCES</span>{permissions.resources.map(r => <div className="resource-row" key={r}><FileText size={14} /><code>{r}</code><LockKeyhole size={13} /></div>)}</div><div className="permission-block"><span className="eyebrow">OUTBOUND DESTINATIONS</span><p className="muted">{permissions.destinations.length ? permissions.destinations.join(", ") : "None permitted. No network executor installed."}</p></div></Panel></div>
    <Panel title="Session history" action={<span className="muted">Recent 30 sessions across all agents</span>}><div className="table-scroll"><table><thead><tr><th>Session</th><th>Created</th><th>Source provenance</th><th>Status</th></tr></thead><tbody>{sessions.map(s => <tr key={s.id}><td className="mono">{shortId(s.id)}…</td><td className="mono muted">{time(s.createdAt)}</td><td>{s.sourceId ?? "Authorized synthetic task"} <Badge value={s.sourceTrust} /></td><td><Badge value={s.active ? "active" : "disabled"} /></td></tr>)}</tbody></table></div></Panel>
    <Panel title="Recent agent events"><ActivityTable navigate={navigate} events={state.events.filter(e => e.actorId === agent.id)} /></Panel></>;
}
export function AgentDNA({ state, focusId, navigate }: SectionProps) {
  const [selected, select] = useState(focusId ?? "research");
  const agent = state.agents.find(a => a.id === selected) ?? state.agents[0];
  if (!agent) return <Empty />;
  const events = state.events.filter(e => e.actorId === agent.id && e.identityVerified);
  const findings = events.filter(e => e.module === "AgentDNA");
  const requests = events.filter(e => e.module === "Gateway" && e.requestId);
  const end = new Date(state.generatedAt).getTime();
  const groups = Array.from({ length: 15 }, (_, i) => requests.filter(e => { const age = end - new Date(e.createdAt).getTime(); return age >= i * 60_000 && age < (i + 1) * 60_000; }));
  const max = Math.max(1, ...groups.map(g => g.length));
  return <><AgentSelector state={state} selected={agent.id} onSelect={select} /><div className="two-column"><Panel title="Behavioral fingerprint" eyebrow={agent.name.toUpperCase()} action={<Badge value={agent.profile?.frozen ? "frozen" : "learning"} />}><div className="baseline-number"><Fingerprint size={32} /><span>{agent.profile?.observations ?? 0}<small>trusted baseline observations</small></span></div><div className="two-bars"><CountBars counts={(agent.profile?.tools ?? {}) as Counts} title="TOOL USAGE" /><CountBars counts={(agent.profile?.resources ?? {}) as Counts} title="RESOURCE ACCESS" /></div><div className="inline-note"><ShieldCheck size={15} />Only permitted activity from trusted sources trains the baseline.</div></Panel><Panel title="Observed activity" eyebrow="VERIFIED REQUESTS · ONE-MINUTE BUCKETS"><div className="activity-chart" aria-label="Verified gateway requests in one-minute time buckets, oldest on left">{groups.toReversed().map((g, i) => <div key={i} className={g.some(e => e.kind === "TOOL_BLOCKED") ? "chart-alert" : ""} style={{ height: `${g.length / max * 140}px` }} title={`${g.length} requests · ${14 - i} minutes ago`} />)}</div><div className="chart-labels"><span>15 minutes ago</span><span>Most recent</span></div><div className="chart-stats"><div><strong>{events.length}</strong><span>recent events</span></div><div><strong className="amber-text">{findings.length}</strong><span>recent deviations</span></div><div><strong>{Object.keys((agent.profile?.sequences ?? {}) as Counts).length}</strong><span>baseline sequences</span></div></div></Panel></div>
    <Panel title="Explainable anomalies" action={<span className="muted">Rule findings · not threat probabilities</span>}>{findings.length ? <div className="finding-list">{findings.map(e => <article className="finding-row" key={e.id}><span className="finding-icon"><Fingerprint size={18} /></span><div><div><code>{e.kind}</code><Badge value={e.severity} /></div><p>{e.message}</p><small className="mono">{time(e.createdAt)} · session {shortId(e.sessionId ?? "")} · evidence {shortId(e.id)}</small>{e.incidentId && <SectionLink onClick={() => navigate("Investigations", e.incidentId!)}>Investigate linked evidence</SectionLink>}</div></article>)}</div> : <Empty title="Behavior matches the observed baseline" detail="Run Memory Poisoning or Full Compromise to test explainable deviations." />}</Panel>
    <Panel title="Typical task sequences"><CountBars title="LEARNED FROM AUTHORIZED ACTIVITY" counts={(agent.profile?.sequences ?? {}) as Counts} /></Panel>
    <Panel title="Historical event sequence" action={<SectionLink onClick={() => navigate("Agent Registry", agent.id)}>Permissions & sessions</SectionLink>}><ActivityTable navigate={navigate} events={events} limit={25} /></Panel></>;
}
export function ShadowWatch({ state, control, busy, navigate }: SectionProps) {
  const violations = state.events.filter(e => e.module === "ShadowWatch");
  const unknown = [...new Set(violations.filter(e => e.kind === "UNKNOWN_IDENTITY").map(e => e.actorId))];
  return <><div className="summary-cards"><div><Radar size={22} /><strong>{state.stats.authorized}</strong><span>Active authorized identities</span></div><div><Ghost size={22} /><strong>{state.stats.unknown}</strong><span>Unknown identities observed</span></div><div><ShieldOff size={22} /><strong>{state.stats.quarantined}</strong><span>Registered agents quarantined</span></div></div>
    <Panel title="Identity & containment" eyebrow="AUTHORIZATION IS ENFORCED BY THE GATEWAY"><div className="table-scroll"><table><thead><tr><th>Agent</th><th>Identity classification</th><th>Trust</th><th>Status</th><th>Response</th></tr></thead><tbody>{state.agents.map(a => <tr key={a.id}><td>{a.name}</td><td>Registered · credential-bound sessions</td><td><Badge value={a.trust} /></td><td><Badge value={a.status} /></td><td><div className="row-controls"><button className="button small danger" disabled={busy || a.status !== "active"} onClick={() => void control("quarantine", a.id)}>Quarantine</button><button className="button small" disabled={busy || a.status === "active"} onClick={() => void control("restore-agent", a.id)}>Restore</button></div></td></tr>)}{unknown.map(id => <tr key={id}><td>{id}</td><td>Unknown · unregistered</td><td><Badge value="unknown" /></td><td><Badge value="blocked" /></td><td><span className="muted">Denied at identity gate</span></td></tr>)}</tbody></table></div></Panel>
    <div className="inline-note"><Shield size={16} />A legitimate identity can be compromised. Linked behavioral and memory findings change trust without changing its registered identity.</div>
    <Panel title="Identity violations & escalation attempts"><ActivityTable navigate={navigate} events={violations} limit={25} /></Panel>
    <Panel title="Auditable response history">{state.actions.length ? <div className="finding-list">{state.actions.map(a => <article className="finding-row" key={a.id}><ShieldCheck size={19} /><div><div><strong>{a.actorId}</strong><Badge value={a.action} /></div><p>{a.reason}</p><small>{a.operator} · {time(a.createdAt)} · action {shortId(a.id)}</small></div></article>)}</div> : <Empty title="No containment actions" detail="Quarantine or revoke an agent to enforce and record a response." />}</Panel></>;
}
export function MemoryGuard({ state, control, busy, focusId, navigate }: SectionProps) {
  const [id, select] = useState<string | null>(focusId ?? null);
  const memory = state.memories.find(m => m.id === id) ?? state.memories[0];
  if (!memory) return <Empty title="No protected memory" detail="Initialize the demonstration to create signed policy memory." />;
  const parent = state.memories.find(m => m.id === memory.parentId);
  const sentences = (s: string) => s.match(/[^.!?]+[.!?]?/g)?.map(v => v.trim()) ?? [s];
  const before = sentences(parent?.content ?? "");
  const after = sentences(memory.content);
  return <><div className="memory-current"><ShieldCheck size={20} /><div><strong>Latest snapshot · v{state.memories[0].version}</strong><p>{state.memories[0].restoredFromId ? "Verified restoration appended; altered history retained." : "Integrity recomputed from content and signed provenance."}</p></div><Badge value={state.memories[0].integrity} /></div><div className="inline-note"><LockKeyhole size={16} />Integrity covers content and provenance. The signing secret is held outside SQLite; a compromised signing key defeats this boundary.</div><div className="memory-grid"><Panel title="Version history" eyebrow="RESEARCH POLICY"><div className="memory-versions">{state.memories.map(m => <button key={m.id} className={memory.id === m.id ? "selected" : ""} onClick={() => select(m.id)}><div><span className="version-icon"><History size={17} /></span><strong>Version {m.version}</strong><Badge value={m.integrity} /></div><p>{m.restoredFromId ? "Verified snapshot restoration" : m.sourceId}</p><small>{time(m.createdAt)} · {m.ownerId}</small></button>)}</div></Panel><Panel title={`Protected memory · v${memory.version}`} action={<Badge value={memory.integrity} />}><div className="memory-content"><span className="eyebrow">CURRENT SELECTED CONTENT</span><p>{memory.content}</p></div><div className="memory-diff"><div><span><i className="diff-minus">−</i> Parent version {parent?.version ?? "—"}</span>{before.map((s, i) => <p key={i} className={!after.includes(s) ? "removed" : ""}>{s || "No parent snapshot"}</p>)}</div><div><span><i className="diff-plus">+</i> Selected version {memory.version}</span>{after.map((s, i) => <p key={i} className={!before.includes(s) ? "added" : ""}>{s}</p>)}</div></div><DetailRow label="Owner / key"><code>{memory.ownerId} / {memory.key}</code></DetailRow><DetailRow label="Source provenance">{memory.sourceId} <Badge value={memory.sourceTrust} /></DetailRow><DetailRow label="Authorization">{memory.authorization}</DetailRow><DetailRow label="Session"><code>{memory.sessionId ? shortId(memory.sessionId) : "System initialization"}</code></DetailRow><DetailRow label="Content SHA-256"><code className="hash-value">{memory.contentHash}</code></DetailRow><DetailRow label="Parent version"><code>{memory.parentId ?? "Root snapshot"}</code></DetailRow><div className="control-row"><button className="button" disabled={busy} onClick={() => void control("verify-memory", memory.id)}><ShieldCheck size={15} />Verify integrity</button><button className="button primary" disabled={busy || memory.integrity !== "verified"} onClick={() => void control("restore-memory", memory.id)}><RotateCcw size={15} />Restore this snapshot</button></div></Panel></div>
    <Panel title="Untrusted source evidence">{state.sources.map(source => <div className="source-document" key={source.id}><div><FileText size={19} /><h3>{source.name}</h3><Badge value={source.trust} /></div><p>{source.content}</p><small className="mono">source://{source.id} · SHA-256 {source.contentHash.slice(0, 20)}…</small></div>)}</Panel>
    <Panel title="Memory integrity events"><ActivityTable navigate={navigate} events={state.events.filter(e => e.module === "MemoryGuard")} limit={20} /></Panel></>;
}
export function GhostTrap({ state, navigate }: SectionProps) {
  const [selected, select] = useState<string | null>(null);
  const trap = state.traps.find(t => t.id === selected);
  const interactions = state.interactions.filter(i => !selected || i.trapId === selected);
  return <><Panel title="Deception topology" eyebrow="SYNTHETIC RESOURCES · LOCAL ONLY" action={<Badge value="active">{state.traps.filter(t => t.active).length} traps armed</Badge>}><AgentNetwork state={state} deception /></Panel><div className="trap-cards">{state.traps.map(t => <button className={`trap-card ${selected === t.id ? "selected" : ""}`} key={t.id} onClick={() => select(selected === t.id ? null : t.id)}><div><Ghost size={21} /><Badge value={t._count.interactions ? "triggered" : "armed"} /></div><h3>{t.name}</h3><p>{t.category}</p><code>{t.resource}</code><div className="trap-card-bottom"><span>{t._count.interactions} interactions</span><ArrowRight size={14} /></div></button>)}</div>{trap && <div className="inline-note"><Ghost size={16} /><span>{trap.description}. Tool: <code>{trap.tool}</code>. No working credentials or external endpoint.</span><button className="text-button" onClick={() => select(null)}>Clear filter</button></div>}
    <Panel title={trap ? `${trap.name} interactions` : "Interaction history"} action={<span className="muted">Interest is evidence, not proof of intent</span>}>{interactions.length ? <div className="table-scroll"><table><thead><tr><th>Time</th><th>Agent / session</th><th>Decoy resource</th><th>Operation</th><th>Investigation</th><th>Evidence</th></tr></thead><tbody>{interactions.map(i => <tr key={i.id}><td className="mono muted">{time(i.createdAt)}</td><td>{i.actorId}<small className="cell-sub">session {shortId(i.sessionId)}</small></td><td>{state.traps.find(t => t.id === i.trapId)?.name}</td><td><code>{i.operation}</code></td><td>{i.incidentId ? <SectionLink onClick={() => navigate("Investigations", i.incidentId!)}>INC-{shortId(i.incidentId).toUpperCase()}</SectionLink> : "Uncorrelated"}</td><td className="mono">{shortId(i.eventId)}</td></tr>)}</tbody></table></div> : <Empty title="Deception resources are armed" detail="The Rogue Agent and Full Compromise scenarios generate actual gateway interaction records." />}</Panel></>;
}
const scenarios = [
  { action: "normal" as const, label: "A", title: "Normal operation", subtitle: "Establish the baseline", icon: Activity, color: "green", description: "Research, operations, and support agents execute 18 permitted tasks. AgentDNA learns and freezes trusted behavior.", expected: "18 allowed · 0 blocked · 0 incidents", button: "Run normal operation" },
  { action: "rogue" as const, label: "B", title: "Rogue agent", subtitle: "Reveal an unknown identity", icon: Radar, color: "cyan", description: "An unregistered actor requests synthetic credentials and an admin MCP decoy. The gateway denies both and records evidence.", expected: "Unknown identity · decoy interaction · blocked", button: "Run rogue scenario" },
  { action: "poisoning" as const, label: "C", title: "Memory poisoning", subtitle: "Protect persistent memory", icon: ShieldCheck, color: "amber", description: "An untrusted attachment prompts policy rewriting and forbidden deployment. Both fail; research completes. A tampered test snapshot is detected and rolled back.", expected: "Write rejected · task completes · snapshot restored", button: "Run memory poisoning" },
  { action: "compromise" as const, label: "D", title: "Full compromise", subtitle: "Connect all four signals", icon: Zap, color: "red", description: "Behavior deviation, memory manipulation, and a decoy interaction correlate into one critical incident. Automatic quarantine blocks an otherwise permitted task; memory is restored.", expected: "Critical incident · quarantine · verified restoration", button: "Run full investigation" }
];
export function DemoControl({ state, control, busy, navigate, result, setResult }: SectionProps & { result: unknown; setResult: (result: unknown) => void }) {
  const [resetConfirm, confirmReset] = useState(false);
  const [replay, setReplay] = useState<{ events: { id: string; module: string; message: string; severity: string }[]; scenario: string } | null>(null);
  const [index, setIndex] = useState(0);
  return <><DemoStory state={state} control={control} busy={busy} navigate={navigate} /><div className="demo-intro"><div><span className="demo-icon"><FlaskConical size={25} /></span><div><h2>Your agent security proving ground</h2><p>Every result comes from the application gateway and persisted evidence. No API keys required.</p></div></div><div className="demo-admin"><button className="button" disabled={busy} onClick={() => void control("initialize")}><Terminal size={15} />Initialize</button><button className="button" disabled={busy} onClick={() => confirmReset(true)}><RotateCcw size={15} />Reset environment</button></div></div>
    {resetConfirm && <div className="reset-confirm" role="alert"><div><strong>Reset synthetic demonstration records?</strong><p>Removes observations, incidents, and memory history; reseeds three agents and five decoys. Signing key and command receipts are retained.</p></div><button className="button" onClick={() => confirmReset(false)}>Cancel</button><button className="button danger" disabled={busy} onClick={async () => { const done = await control("reset"); if (done) { confirmReset(false); setReplay(null); setResult(null); } }}>Reset demo records</button></div>}
    <div className="scenario-grid">{scenarios.map(({ action, label, title, subtitle, icon: Icon, color, description, expected, button }) => <article className={`scenario-card ${color}`} key={action}><div className="scenario-top"><span className={`engine-icon ${color}`}><Icon size={23} /></span><span className="scenario-letter">SCENARIO {label}</span></div><h2>{title}</h2><h3>{subtitle}</h3><p>{description}</p><div className="scenario-expected"><CheckCheck size={15} />{expected}</div><button className={`button ${action === "compromise" ? "primary" : ""}`} disabled={busy || !state.agents.length || state.agents.some(a => a.status !== "active") && ["normal", "poisoning", "compromise"].includes(action)} onClick={async () => { setReplay(null); await control(action); }}><Play size={13} fill="currentColor" />{busy ? "Processing…" : button}<ArrowRight size={15} /></button></article>)}</div>
    {state.agents.some(a => a.status !== "active") && <div className="inline-note"><ShieldOff size={16} />A registered agent is contained. Restore it in ShadowWatch or reset the environment before running scenarios that need that agent.<SectionLink onClick={() => navigate("ShadowWatch")}>Response controls</SectionLink></div>}
    <div className="two-column"><Panel title="Backend result inspector" eyebrow="LATEST COMMAND RECEIPT" action={<Code size={17} className="muted" />}>{result ? <pre className="result-json">{JSON.stringify(result, null, 2)}</pre> : <Empty title="Ready for a live demonstration" detail="Execute any scenario to inspect its actual policy decisions, incident IDs, and memory results." />}</Panel><Panel title="Run history" eyebrow="PERSISTED SIMULATION RUNS">{state.runs.length ? <div className="run-history">{state.runs.map(r => <div key={r.id}><span className="run-icon"><Terminal size={18} /></span><div><strong>{r.scenario.replaceAll("-", " ")}</strong><small>{time(r.startedAt)} · {shortId(r.id)} · <Badge value={r.status} /></small></div><button className="button small" disabled={busy} onClick={async () => { const result = await control("replay", r.id); if (result) { setReplay(result as NonNullable<typeof replay>); setIndex(0); } }}><History size={13} />Replay</button></div>)}</div> : <Empty title="No runs recorded" detail="Your simulation history appears here after execution." />}</Panel></div>
    {replay && <Panel title={`Evidence replay · ${replay.scenario}`} eyebrow="READ-ONLY PLAYBACK · NO ACTIONS RE-EXECUTED" action={<Badge value="info">{index + 1} / {replay.events.length}</Badge>}><div className="replay-view"><Badge value={replay.events[index]?.module ?? "info"} /><p>{replay.events[index]?.message}</p><small className="mono">event {replay.events[index]?.id}</small><input type="range" aria-label="Replay event" min={0} max={Math.max(0, replay.events.length - 1)} value={index} onChange={e => setIndex(Number(e.target.value))} /><div className="control-row"><button className="button" disabled={index === 0} onClick={() => setIndex(i => i - 1)}>Previous event</button><button className="button primary" disabled={index >= replay.events.length - 1} onClick={() => setIndex(i => i + 1)}>Next event<ArrowRight size={14} /></button></div></div></Panel>}
    <div className="demo-finish"><Clock size={20} /><div><strong>A two-minute investigation</strong><p>Run A → B → C → D. Open Investigations to inspect the critical timeline, then MemoryGuard to verify restoration. The final blocked request proves containment.</p></div><button className="button" onClick={() => navigate("Investigations")}>Open investigations<ArrowRight size={15} /></button></div>
  </>;
}
