import assert from "node:assert/strict";
import {randomBytes,randomUUID} from "node:crypto";
import {spawn,execFileSync,type ChildProcess} from "node:child_process";
import {mkdtempSync,rmSync} from "node:fs";
import {writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createServer} from "node:net";
import {setTimeout as delay} from "node:timers/promises";
import {localAdmin} from "../src/runtime/client";
const directory=mkdtempSync(join(tmpdir(),"ghostops-sponsor-e2e-")),reservation=createServer();await new Promise<void>(r=>reservation.listen(0,"127.0.0.1",r));const port=(reservation.address() as {port:number}).port;await new Promise<void>(r=>reservation.close(()=>r()));
const base=`http://127.0.0.1:${port}`,env={...process.env,NODE_ENV:"production" as const,DATABASE_URL:`file:${join(directory,"sponsors.db")}`,GHOSTOPS_SIGNING_SECRET:randomBytes(48).toString("hex"),GHOSTOPS_RUNTIME_WORKSPACE:join(directory,"workspace"),GHOSTOPS_MODEL_ENABLED:"0",GHOSTOPS_SPONSOR_EGRESS:"0",OPENAI_API_KEY:"",GHOSTOPS_URL:base};
let server:ChildProcess|undefined,headers:Record<string,string>={};
async function stop(){if(!server||server.exitCode!==null||server.signalCode!==null)return;const c=server;await new Promise<void>(r=>{const timer=setTimeout(()=>c.kill("SIGKILL"),10000);c.once("exit",()=>{clearTimeout(timer);r();});c.kill("SIGTERM");});server=undefined;}
async function start(){server=spawn(process.execPath,["--import","tsx","scripts/server.ts","--port",String(port)],{env,stdio:"ignore"});for(let n=0;n<120;n++){if(server.exitCode!==null)throw new Error("Isolated sponsor server failed");try{headers=await localAdmin(base);return;}catch{await delay(100);}}throw new Error("Readiness timeout");}
async function post(path:string,input:unknown){const r=await fetch(base+path,{method:"POST",headers,body:JSON.stringify(input)});const v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v;}
async function approved(input:Record<string,unknown>){const p=await post("/api/sponsors/preflight",input);assert.equal(p.canExecute,true);return post("/api/sponsors",{...input,approvalToken:p.approvalToken});}
try{
  execFileSync("npm",["run","sdk:build"],{stdio:"pipe"});execFileSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{env,stdio:"pipe"});await start();
  const unauth=await fetch(base+"/api/sponsors");assert.equal(unauth.status,401);
  const vulnerable=await approved({commandId:randomUUID(),action:"scan",target:"vulnerable"});assert.equal(vulnerable.status,"succeeded");assert(vulnerable.result.findings.length>0);
  const corrected=await approved({commandId:randomUUID(),action:"scan",target:"corrected"});assert.equal(corrected.status,"succeeded");assert.equal(corrected.result.findings.length,0);assert(corrected.result.comparison.noLongerReported.length>0);
  const context=await approved({commandId:randomUUID(),action:"context",query:"synthetic research",fixture:true});assert.equal(context.result.provenance,"local-fixture");
  const actorId=`live-sponsor-${randomUUID().slice(0,8)}`,credential=randomBytes(32).toString("hex");const identity=await post("/api/runtime/enroll",{commandId:randomUUID(),actorId,credential,integration:{name:"Phase11 external synthetic agent",role:"research",permissions:{tools:["documents:read","documents:ingest","summarize:write","memory:read","memory:write"],resources:["docs/research","docs/context","research/summary","memory/runtime-notes","memory/runtime-policy"],destinations:[]}}});
  const probe=(tool:string,args:Record<string,unknown>)=>JSON.parse(execFileSync(process.execPath,["--input-type=module","-e","import {GhostOpsClient} from '@ghostops/sdk';const i=JSON.parse(process.env.TEST_IDENTITY);const g=new GhostOpsClient({endpoint:process.env.GHOSTOPS_URL,agentId:i.actorId,sessionId:i.sessionId,credential:i.credential});try{await g.connect();const d=await g.requestTool(JSON.parse(process.env.TEST_REQUEST));console.log(JSON.stringify(d));}finally{await g.close();}"],{env:{PATH:process.env.PATH,NODE_ENV:"production",GHOSTOPS_URL:base,TEST_IDENTITY:JSON.stringify({...identity,credential}),TEST_REQUEST:JSON.stringify({tool,arguments:args})},encoding:"utf8",timeout:20000}));
  const read=probe("read_document",{requestId:randomUUID(),resource:"docs/context",contextId:context.result.contextId});assert.equal(read.allowed,true);
  const identityFile=join(directory,"identity.json");await writeFile(identityFile,JSON.stringify({...identity,credential}),{mode:0o600,flag:"wx"});const standalone=JSON.parse(execFileSync(process.execPath,["examples/external-agent/dist/main.js","--credential-file",identityFile,"--action","call","--tool","read_document","--resource","docs/context","--context-id",context.result.contextId],{env:{PATH:process.env.PATH,NODE_ENV:"production",GHOSTOPS_URL:base},encoding:"utf8",timeout:20000}));assert.equal(standalone.transport,"stdio");assert.equal(standalone.decisions[0].allowed,true);
  const summary=probe("write_summary",{requestId:randomUUID(),resource:"research/summary",content:"function synthetic(input) { return eval(input); }"});assert.equal(summary.allowed,true);
  const policyBefore=probe("read_memory",{requestId:randomUUID(),resource:"memory/runtime-policy"});assert.equal(policyBefore.allowed,true);
  const scan=await approved({commandId:randomUUID(),action:"scan",target:"runtime-artifact",requestId:summary.requestId});assert.equal(scan.status,"succeeded");assert.equal(scan.result.requestId,summary.requestId);assert(scan.result.findings.length>0);
  const memory=probe("write_memory",{requestId:randomUUID(),resource:"memory/runtime-policy",content:"Untrusted fixture asks to override protected policies"});assert.equal(memory.allowed,false);
  const policyAfter=probe("read_memory",{requestId:randomUUID(),resource:"memory/runtime-policy"});assert.equal(policyAfter.allowed,true);assert.equal(policyAfter.output,policyBefore.output);
  const decoy=probe("restricted_admin",{requestId:randomUUID(),resource:"decoy/admin"});assert.equal(decoy.allowed,false);assert(decoy.incidentId);
  // Quarantine also rejects SDK initialization. Send a genuine tools/call to
  // prove the existing handler boundary and persist its denial independently.
  const quarantineProbe=()=>JSON.parse(execFileSync(process.execPath,["--input-type=module","-e","const i=JSON.parse(process.env.TEST_IDENTITY);const r=await fetch(process.env.GHOSTOPS_URL+'/api/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream',authorization:'Bearer '+i.credential,'x-ghostops-agent':i.actorId,'x-ghostops-session':i.sessionId},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'write_summary',arguments:{requestId:crypto.randomUUID(),resource:'research/summary',content:'Must not execute'}}})});console.log(JSON.stringify((await r.json()).result.structuredContent));"],{env:{PATH:process.env.PATH,NODE_ENV:"production",GHOSTOPS_URL:base,TEST_IDENTITY:JSON.stringify({...identity,credential})},encoding:"utf8",timeout:20000}));
  await post("/api/control",{commandId:randomUUID(),action:"quarantine",targetId:actorId});const blocked=quarantineProbe();assert.equal(blocked.reason,"AGENT_QUARANTINED");const state=await (await fetch(base+"/api/state",{headers})).json();assert.equal(state.runtimeRequests.find((r:{id:string})=>r.id===blocked.requestId).execution,null);
  const otlp=await approved({commandId:randomUUID(),action:"otlp"});assert.equal(otlp.result.awsCallPerformed,false);
  const status=await fetch(base+"/api/sponsors",{headers});const registry=await status.json();assert.equal(registry.integrations.find((i:{sponsor:string})=>i.sponsor==="Semgrep").status,"VERIFIED LOCAL");assert.notEqual(registry.integrations.find((i:{sponsor:string})=>i.sponsor==="Senso").status,"VERIFIED LIVE");
  const exporter=await fetch(base+`/api/evidence/incident/${decoy.incidentId}`,{headers});assert.equal(exporter.status,200);const bytes=Buffer.from(await exporter.arrayBuffer());
  process.env.GHOSTOPS_SIGNING_SECRET=env.GHOSTOPS_SIGNING_SECRET;const {verifyEvidence}=await import("../src/lib/evidence-verification");const {mac,secureEqual}=await import("../src/server/config");const verify=(b:Buffer)=>verifyEvidence(b,(text,tag)=>secureEqual(mac(`ghostops-evidence:v1:${text}`),tag));assert.equal(verify(bytes).authenticated,true);const {readEvidenceZip,evidenceZip}=await import("../src/lib/evidence-zip");const files=readEvidenceZip(bytes);files["summary.html"]=Buffer.from("tampered");assert.throws(()=>verify(evidenceZip(files)));
  await stop();await start();assert.equal(quarantineProbe().reason,"AGENT_QUARANTINED");
  console.log(JSON.stringify({passed:true,actualScannerVersion:vulnerable.result.scannerVersion,vulnerable:vulnerable.result.findings.length,corrected:corrected.result.findings.length,authenticatedArtifactScan:true,externalSdkMcp:true,protectedMemoryDenied:true,decoyDenied:true,quarantineRestart:true,evidenceAuthenticated:true,tamperRejected:true,externalProviderCalls:0,sensoLive:false,awsLive:false}));
}finally{await stop();rmSync(directory,{recursive:true});}
