import Link from 'next/link';
import { StoryShell } from '../components/story-shell';
import { StoryIllustration } from '../components/story-illustrations';
const scenes=[
['problem','01','THE PROBLEM','AUTONOMY HAS','A THREAT SURFACE.','Agents read untrusted content, request powerful tools and carry context forward. Security needs a decision boundary and an inspectable record.','OBSERVE BEHAVIOR. VERIFY AUTHORITY.','alert'],
['agentdna','02','AGENTDNA / BEHAVIOR','KNOW THE PATTERN.','NOTICE THE DRIFT.','Compare authenticated tool sequences with trusted behavioral baselines. Explainable deviations give investigators a place to look.','A SIGNAL TO INVESTIGATE. NOT A COMPROMISE PROBABILITY.','investigating'],
['shadowwatch','03','SHADOWWATCH / IDENTITY','A CLAIM IS','NOT A CREDENTIAL.','Bind requests to verified identities and current sessions. Enforce scoped permissions, revocation and containment before a tool runs.','IDENTITY BEFORE AUTHORITY.','alert'],
['memoryguard','04','MEMORYGUARD / INTEGRITY','PROTECT WHAT','THE AGENT REMEMBERS.','Inspect signed content and provenance, compare historical versions and reject protected-memory writes. Local restoration requires a verified snapshot.','SIGNING-KEY AND HOST TRUST STILL MATTER.','happy'],
['ghosttrap','05','GHOSTTRAP / DECEPTION','LEAVE A DECOY.','FOLLOW THE INTEREST.','Inert synthetic resources record attempted access without exposing real secrets. Correlate the interaction with independent evidence.','DECOY CONTACT DOES NOT PROVE INTENT.','happy'],
['hunt','06','GHOST HUNT + GHOST RESPONSE','CONNECT THE TRAIL.','CONTROL THE RESPONSE.','Follow evidence across agents, sessions and resources. Reviewed containment uses the gateway boundary; denied follow-up requests verify enforcement.','FACTS, INTERPRETATION AND RESPONSE REMAIN DISTINCT.','investigating'],
['gateway','07','MCP SECURITY GATEWAY','BEFORE THE TOOL.','CHECK THE BOUNDARY.','Current identity, session, credential, operation, resource and destination checks precede bounded effects. Every supported request leaves a decision receipt.','UNINTEGRATED OS ACTIVITY IS OUTSIDE THIS BOUNDARY.','alert'],
['sentinel','08','WEB SENTINEL / INTELLIGENCE','RESEARCH THE SOURCE.','KEEP THE RECEIPTS.','The local platform supports approved advisory retrieval, scoped code analysis and source-grounded report preparation. Publishing requires exact-content approval.','THIS WEBSITE DOES NOT EXECUTE RESEARCH, SCANS OR PUBLISHING.','investigating'],
['evidence','09','FORENSIC EVIDENCE','EVERY DECISION.','AN INSPECTABLE TRAIL.','Open chronological evidence, compare memory versions and verify minimized exports. Integrity checks establish consistency under explicit local-key trust assumptions.','RECORDED CHRONOLOGY. NO FABRICATED LIVE ACTIVITY.','happy'],
];
export default function Home(){return <StoryShell><main id="story-main" className="story-main" tabIndex={-1}>
<section id="hero" className="story-hero forest-grid" data-ghost-scene="hero" data-expression="idle"><div className="sheet-rail"><span>AUTONOMOUS AI COUNTERINTELLIGENCE</span><span>SYSTEM / GHOST OPS</span></div><div className="hero-composition"><div className="story-hero-copy"><p className="technical-label"><i/>AUTHORITY BEFORE EFFECTS</p><h1>YOUR AGENTS<br/>ARE WORKING.<br/><span>WE&apos;RE<br/>WATCHING.</span></h1><p className="story-intro">Ghost Ops monitors autonomous AI agents, detects suspicious behavior, protects persistent memory, and enforces security boundaries before unauthorized tool actions execute.</p><div className="story-actions"><Link href="/terminal/" className="story-button primary" data-enter-terminal>ENTER GHOST OPS <span>↗</span></Link><a href="#problem" className="story-button secondary">EXPLORE THE SYSTEM <span>↓</span></a></div></div><div className="hero-art"><div className="mascot-slot"/></div></div><div className="hero-bottom"><span>BEHAVIOR / IDENTITY / MEMORY / EVIDENCE</span><span>PUBLIC WORKSTATION: RECORDED DATA ONLY</span><a href="#problem">SCROLL TO INSPECT ↓</a></div></section>
{scenes.map(([id,number,label,title,accent,copy,note,expression],i)=><section key={id} id={id} className={`story-sheet ${i===3||i===7?'forest-grid':''}`} data-ghost-scene={id} data-expression={expression}><div className="sheet-rail"><span>{number} / {label}</span><span>GHOST OPS / SYSTEM SHEET</span></div><div className="scene-composition"><div className="scene-copy"><h2>{title}<br/><span>{accent}</span></h2><p>{copy}</p><StoryIllustration kind={id}/><div className="sheet-note">{note}</div></div><div className="scene-art"><div className="mascot-slot"/></div></div><div className="sheet-stamp"><span>GHOST OPS / COUNTERINTELLIGENCE</span><span>ILLUSTRATIVE SYSTEM DIAGRAM</span><span>{number} / 09 ↗</span></div></section>)}
<section id="enter" className="story-closing forest-grid" data-ghost-scene="enter" data-expression="happy"><div className="sheet-rail"><span>THE WORKSTATION / ENTER</span><span>YOUR NEXT INVESTIGATION</span></div><div className="scene-composition"><div className="scene-copy"><h2>ENTER<br/><span>THE SYSTEM.</span></h2><p>The real Ghost Ops workstation. Explore the agent network, arrange your windows, inspect recorded evidence and follow a guided investigation.</p><Link href="/terminal/" className="story-button primary" data-enter-terminal>OPEN GHOST OPS <span>→</span></Link><p className="closing-scope">Interactive recorded demonstration. Live agents and privileged backend operations remain local.</p><Link href="/docs/" className="text-route">LOCAL DEVELOPER SETUP ↗</Link></div><div className="scene-art terminal-entrance"><div className="mascot-slot"/><span>GHOST OPS TERMINAL / READY TO EXPLORE</span><div className="entrance-line"/></div></div></section>
</main></StoryShell>;}
