'use client';
import { useState } from 'react';
import { Panel, Badge, time } from '@/components/ui';
import { workstationState, playbackEvents } from '../data/workstation-state';
import record from '../data/recorded-case.json';

export function BackendBoundary() { return <p className="inline-note">Recorded sample case. Scans, inference, credentials, quarantine, memory restoration, authenticated exports and GitHub publication require the local backend. <a href="/docs/">Developer setup</a></p>; }
export function RecordedLab() { const [selected,setSelected]=useState('protected-write');return <div className="recorded-panel"><Panel title="Security Lab" eyebrow="RECORDED SYNTHETIC EXPERIMENTS"><BackendBoundary /><label>Recorded experiment<select aria-label="Recorded experiment" value={selected} onChange={e=>setSelected(e.target.value)}><option value="protected-write">Protected write denial</option><option value="decoy">Decoy interaction</option></select></label><p>{selected==='decoy'?'A synthetic decoy was accessed. Interest alone does not establish malicious intent.':'The recorded protected-write request was rejected before the handler executed.'}</p>{record.events.filter(e=>selected==='decoy'?e.kind==='DECOY_INTERACTION':e.kind.includes('WRITE')).map(e=><details key={e.id}><summary>{e.kind} · {time(e.at)}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}<button className="button" disabled>Start experiment — local backend required</button><button className="button" disabled>Run model — local backend required</button></Panel></div>; }
export function RecordedHunt({navigate}:{navigate:(name:string,id?:string)=>void}) {const [category,setCategory]=useState('all');const [selected,setSelected]=useState<string>();const events=playbackEvents.filter(e=>category==='all'||(category==='denied'?e.kind.includes('BLOCKED'):e.kind==='DECOY_INTERACTION'));return <div className="recorded-panel"><Panel title="Ghost Hunt + Ghost Response" eyebrow="RECORDED EVIDENCE / DISPLAY ONLY"><BackendBoundary /><p>Evidence-linked investigation: inspect events, focus the actual agent network or open the recorded case. Response is a historical outcome, never an action on this website.</p><button className="button" onClick={()=>navigate('Agent network')}>Explore agent network</button><button className="button" onClick={()=>navigate('Investigations','demo-case')}>Open recorded investigation</button><label>Evidence category<select aria-label="Recorded hunt category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All evidence</option><option value="denied">Policy denials</option><option value="interest">Decoy interest</option></select></label>{events.map(e=><details key={e.id} open={e.id===selected}><summary onClick={()=>setSelected(e.id)}>#{e.ordinal} / {e.module} / {e.kind}</summary><p>{e.message}</p><time>{time(e.createdAt)}</time><button className="button" onClick={()=>navigate('Evidence',e.id)}>Inspect evidence</button></details>)}<h3>Ghost Response</h3><Badge value="quarantined">Recorded quarantine outcome</Badge><p>Quarantine is present in the minimized recording. No public enforcement or response execution is available.</p><button className="button" disabled>Approve response — local backend required</button></Panel></div>; }
export function RecordedSponsors() {return <div className="recorded-panel"><Panel title="Sponsor Integrations" eyebrow="CAPABILITY STATUS / NO REMOTE CONNECTIONS"><BackendBoundary />{[['Guild.ai','Agent runtime: awaiting an approved workspace and real session receipt'],['ClickHouse','Security analytics: awaiting a real server insert/query receipt'],['Akash','Persistent compute: awaiting approved account access, credits and a verified lease']].map(([name,status])=><section className="inspector-section" key={name}><h3>{name}</h3><span className="eyebrow">AWAITING CONNECTION</span><p>{status}</p></section>)}</Panel></div>; }
export function RecordedSentinel() {const [selected,setSelected]=useState(record.events[0].id);const event=record.events.find(e=>e.id===selected)!;return <div className="recorded-panel"><Panel title="Web Sentinel" eyebrow="RECORDED SYNTHETIC EVIDENCE"><BackendBoundary /><p>{record.label}. Recorded at {time(record.recordedAt)}. This website retrieves no advisories, runs no scanner, and publishes no reports.</p><label>Sentinel evidence<select aria-label="Sentinel recorded event" value={selected} onChange={e=>setSelected(e.target.value)}>{record.events.map(e=><option key={e.id} value={e.id}>#{e.ordinal} / {e.kind}</option>)}</select></label><pre>{JSON.stringify(event,null,2)}</pre><button className="button" disabled>Start bounded run — local backend required</button><button className="button" disabled>Publish GitHub report — local backend required</button></Panel></div>; }
export function RecordedRuntime() {return <div className="recorded-panel"><Panel title="Developer Integrations" eyebrow="RECORDED SESSION / NO ACTIVE MCP SESSION"><BackendBoundary /><p>The three graph identities are illustrative simulated agents. No external agent is connected to this public site. MCP gateway receipts remain on the authenticated local backend.</p><a className="button" href="/docs/">SDK and MCP setup documentation</a><h3>Simulated agent capabilities</h3>{workstationState.agents.map(a=><details key={a.id}><summary>{a.name}</summary><pre>{JSON.stringify(a.permissions,null,2)}</pre></details>)}<button className="button" disabled>Provision credential — local backend required</button></Panel></div>; }
