import type { ReactNode } from 'react';
function Frame({label,children}:{label:string;children:ReactNode}){return <div className="technical-figure"><div className="figure-label"><span>{label}</span><span>ILLUSTRATIVE / OFFLINE</span></div>{children}</div>;}
export function StoryIllustration({kind}:{kind:string}){
 if(kind==='problem')return <Frame label="THREAT SURFACE"><div className="threat-lines">{['Authority outlives intent.','Claims need a verified binding.','Context becomes a target.'].map((s,i)=><p key={s}><span>0{i+1} / BOUNDARY</span><strong>{s}</strong></p>)}</div></Frame>;
 if(kind==='agentdna')return <Frame label="BEHAVIORAL FINGERPRINT"><div className="fingerprint" aria-label="Illustrative trusted baseline and deviation">{[25,48,32,70,42,62,35,51,88,37,68,43,29,53,80,40,62,35,76,47].map((h,i)=><i key={i} style={{height:`${h}%`}} className={i===8?'deviation':''}/>)}</div><div className="figure-foot"><span>TRUSTED BASELINE</span><span className="warning-text">DEVIATION ≠ MALICIOUS INTENT</span></div></Frame>;
 if(kind==='shadowwatch')return <Frame label="IDENTITY / AUTHORIZATION"><div className="identity-line"><span className="figure-ok">VERIFIED BINDING</span><code>agent/research</code><b>SCOPED</b></div><div className="identity-line"><span className="figure-denied">UNVERIFIED CLAIM</span><code>claimed/admin</code><b>DENIED</b></div><p className="figure-note">Identity → session → current credential → capability</p></Frame>;
 if(kind==='memoryguard')return <Frame label="MEMORY / PROVENANCE"><div className="memory-sheet"><span>POLICY / PROTECTED</span><code>read approved documents<br/>preserve source provenance<br/><mark>reject unauthorized changes</mark></code></div><div className="figure-foot"><span>VERSION CHAIN / INTEGRITY</span><span className="figure-ok">VERIFY BEFORE RESTORE</span></div></Frame>;
 if(kind==='ghosttrap')return <Frame label="DECEPTION / SYNTHETIC CATALOG"><div className="decoy-file"><span>◇</span><code>decoy/admin</code><b className="warning-text">INERT RESOURCE</b></div><p className="figure-note">Attempted access leaves evidence.<br/>Interest alone does not establish intent.</p></Frame>;
 if(kind==='hunt')return <Frame label="CORRELATION / INVESTIGATION"><div className="hunt-trail"><span>AGENT A</span><i>→</i><span>REQUEST</span><i>→</i><span>AGENT B</span></div><div className="response-line"><code>memory:write / protected-policy</code><b className="figure-denied">DENIED / NO HANDLER EFFECT</b></div><p className="figure-note">Linked evidence → reviewed response → verified follow-up</p></Frame>;
 if(kind==='gateway')return <Frame label="MCP / DECISION BEFORE EFFECT"><ol className="gateway-flow"><li>AGENT</li><li>GUARDED TOOL REQUEST</li><li>POLICY DECISION</li><li><span className="figure-ok">AUTHORIZED → BOUNDED HANDLER</span><span className="figure-denied">DENIED → NO EFFECT</span></li></ol><p className="figure-note">Only supported, integrated gateway-routed operations.</p></Frame>;
 if(kind==='sentinel')return <Frame label="WEB SENTINEL / LOCAL CAPABILITY"><div className="research-terminal"><span>RESEARCH PLAN / EXPLICIT APPROVAL</span><code>01 / allowlisted public sources<br/>02 / approved repository scope<br/>03 / source-grounded findings<br/>04 / exact report preview</code><b>PUBLIC DEMO: NO SCAN OR EXTERNAL REQUEST</b></div></Frame>;
 return <Frame label="FORENSICS / PRESERVED CHRONOLOGY"><ol className="evidence-story">{['Request + policy decision','Correlated investigation','Minimized evidence export','Manifest + integrity verification'].map((s,i)=><li key={s}><span>0{i+1}</span>{s}</li>)}</ol><p className="figure-note">Local-key authentication has host/key trust limits.</p></Frame>;
}
